### ISSUE TITLE
Is it possible to have multiple objective functions one for output of the network ant the others for the intermediate layers ?

### ISSUE THREAD

**Issue by erogol** [dnouri/nolearn#105]
I attempt to train a multi-objective network that includes one for label prediction of the output layer and two more for the intermediate layer's prediction like the GoogLenet. Is it viable with nolearn lasagne interface?

**Comment by dnouri** [comment]
If these intermediate objectives use the same target, then this should be pretty straight forward.  Here's some sample code to get you started:

```python
class MyObjective(Objective):
    def get_loss(self, input=None, target=None, deterministic=False, **kwargs):
        net_out, interm_out = get_output(
            [self.input_layer, self.layers['indermediate']],
            input, **kwargs
            )
        if target is None:
            target = self.target_var
        losses = self.loss_function(net_out, target) + self.loss_function(interm_out, target)
        return losses.mean()
```

Then, when instantiating NeuralNet, pass the parameter `objective=MyObjective`.

The code is untested, let me know if it has any issues, and I'll correct it here.  But it'll hopefully give you an idea.

**Comment by dnouri** [comment]
So #124 was just merged which means that the class posted above will no longer work.  Instead, you should use something like this `my_objective` and pass it as the `objective` parameter:

```python
def my_objective(layers,
                 loss_function,
                 target,
                 aggregate=aggregate,
                 deterministic=False,
                 get_output_kw=None):
    if get_output_kw is None:
        get_output_kw = {}
    net_out, interm_out = get_output(
        [layers[-1], layers['indermediate']],
        deterministic=deterministic,
        **get_output_kw
        )
    losses = loss_function(net_out, target) + loss_function(interm_out, target)
    return aggregate(losses)
```
