### ISSUE TITLE
Different ways to install the packet

### ISSUE THREAD

**Issue by pattysan** [dnouri/nolearn#112]
Hello, I tried to install the packet using pip as you suggest in the docs but I have some internet access problems from the command windows so I can't install it. I also tried in the old fashion, that means  download the .zip , unzip and  run $ python setup.py install    but it doesn' work. Any other idea? Thank you

**Comment by BenjaminBossan** [comment]
It's hard to tell what the problem is from the information you provide. Could you be more specific about the error message? Have you managed to successfully install all requirements?

**Comment by pattysan** [comment]
Finally, I solved using the way you suggest with  pip  but I had to add the proxy line since I can't  have the direct  access to internet, but I think it would be better to provide an alternative way to  install the packet (using python setup.py install from the download packet),I tried it but  it gave some errors. I can't report them because I am now using another pc but you can try and see if it was only my problem or it is a general one.

**Comment by dnouri** [comment]
Using setup.py likely triggers the same issue: it has to download additional packages from the internet.  If you want to install on a computer without internet connection, you'll need to download nolearn and all its dependencies first, then transfer and use pip to install from the downloaded files.
