### ISSUE TITLE
Improve train_test_split

### ISSUE THREAD

**Issue by cancan101** [dnouri/nolearn#12]
For `NeuralNet`:
1) Why use your own implementation of `train_test_split` rather than using [`sklearn.cross_validation::train_test_split`](https://github.com/scikit-learn/scikit-learn/blob/cedaf1f867b107bc1ee6e3172a8df0268837322f/sklearn/cross_validation.py#L1655)?
-- This would fix #7 because it uses [`safe_indexing`](https://github.com/scikit-learn/scikit-learn/blob/f0fe4afd1ee3c19ed13a13f25573f9c173e9e65b/sklearn/utils/__init__.py#L135).
2) Allow the user to pass in, through composition (like the batch iterator), a class responsible for performing the train vs valid split. Right now the only option is to subclass `NeuralNet` which is not ideal.

**Comment by dnouri** [comment]
@cancan101 To answer your first question: You'll notice that `NeuralNet.train_test_split` uses `StratifiedKFold` for classification tasks.  That's different to what sklearn's `train_test_split` would give you.

But maybe the stratified split isn't all that important, and we can just use an overridable train_test_split (component) by default.

**Comment by dnouri** [comment]
I think we can merge this discussion with #42, and close this one.  Also consider #45 when thinking about a better way to override the `train_test_split` method.
