### ISSUE TITLE
Convolution Network - Accuracy results

### ISSUE THREAD

**Issue by Temmplar** [dnouri/nolearn#132]
Dear Daniel,
I have an issue, I hope you will help me.
I'm trying to get accuracy information from a convolutional net. 
If I chose regression it works fine. If I choose classification I get an output like this:

 epoch    train loss    valid loss    train/val    valid acc  dur
-------  ------------  ------------  -----------  -----------  ------
      1       0.50873       0.60935      0.83488      0.79269  11.24s
      2       0.50304       0.58649      0.85771      0.79269  11.91s
      3       0.49532       0.57172      0.86637      0.79269  11.89s
      4       0.49352       0.55105      0.89560      0.79269  11.92s
      5       0.49049       0.53669      0.91392      0.79269  11.75s
      6       0.48861       0.52467      0.93127      0.79269  11.64s

I am newbie on this domain and I'd like to know:
Is this a normal result?
My question is that why the accuracy doesn't change?
At the regression task the train and valid losses were like 0.18, 0.16.

Thank you in advance.
George

**Comment by dnouri** [comment]
What are you trying to predict?  Looks like it's giving you the same answer for all examples.  I'd guess that 80% of your examples have the same class.  Not a problem per se; what if you let it run for a while?  Or you lower learning rate?

I'll close this since this isn't an issue with nolearn really.  Good luck.

**Comment by Temmplar** [comment]
Thank you for the answer, I am about to try the things you proposed.
I don't really know if this is the legal place I may ask, but can I work with DBN inside of platform of nolearn?

**Comment by dnouri** [comment]
Try to introspect your data.  Maybe you're doing some processing and it ends up garbled?  Maybe the task is impossible to solve also for humans?  As I said, it's very hard to say with the kind of information that you've provided.  And this isn't the appropriate place to ask.

**Comment by Temmplar** [comment]
OK Daniel, thanks for your answer, anyway the data would be solvable as this is a Kaggle thing, but I just want to make sure if this is a known special symptom of doing something wrong, so for a week or too I introspect any aspect including the data of course as well. Thank you for your time.

**Comment by cancan101** [comment]
@dnouri what do you think about a nolearn mailing list?

**Comment by dnouri** [comment]
@cancan101 I was hoping to avoid having a separate mailing list.  People on the lasagne mailing list agreed that if it's a lasagn-ish problem, but code based on nolearn, it's good to post there.

**Comment by cancan101** [comment]
Ok. Probably worth noting blurring this in reqdme.
