### ISSUE TITLE
Remove sudo requirement from .travis.yml file

### ISSUE THREAD

**Issue by cancan101** [dnouri/nolearn#133]
Using miniconda + sudo should not be required.

Instead you can make sure to install the new version of `pip` and then enable pip caching in travis. This should lead to creation and caching of wheels which will speed up builds.

**Comment by dnouri** [comment]
Can you explain which sudo you're talking about?

Good point about pip caching.

**Comment by cancan101** [comment]
by `sudo` I mean the old travis-ci infrastructure (and the fact that you use sudo in the `.travis.yml` file).
See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/

**Comment by dnouri** [comment]
Fixed a while ago
