### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by necludov** [dnouri/nolearn#139]
Sorry for possible stupid question. I've spent two days to install nolearn to run some script from kaggle competition ( https://www.kaggle.com/bitsofbits/grasp-and-lift-eeg-detection/naive-nnet/code ). I've tried some ways to install Lasagne and nolearn but with no success. Now i just install nolearn using two commands from description, install actual version of Lasagne from git and got an error:

______________________________________________
```
ImportError                               Traceback (most recent call last)
<ipython-input-1-ff9cbd6f0819> in <module>()
     13 # Lasagne (& friends) imports
     14 import theano
---> 15 from nolearn.lasagne import BatchIterator, NeuralNet
     16 from lasagne.objectives import aggregate, binary_crossentropy
     17 from lasagne.layers import InputLayer, DropoutLayer, DenseLayer,Conv1DLayer,MaxPool1DLayer

/usr/local/lib/python2.7/dist-packages/nolearn/lasagne/\__init\__.py in <module>()
      4     SaveWeights,
      5     )
----> 6 from .base import (
      7     BatchIterator,
      8     objective,

/usr/local/lib/python2.7/dist-packages/nolearn/lasagne/base.py in <module>()
      1 from \__future\__ import absolute_import
      2 
----> 3 from .._compat import basestring
      4 from .._compat import chain_exception
      5 from .._compat import pickle

ImportError: cannot import name basestring
```
_______________________________________________
I'll be very thankful, if you can help me.

**Comment by dnouri** [comment]
Hmm, looks like something went wrong with the installation.  Best to remove Lasagne again and [follow the installation instructions](https://github.com/dnouri/nolearn#installation).
