### ISSUE TITLE
Which non-linearity to use for regression problem in final layer

### ISSUE THREAD

**Issue by cbonnett** [dnouri/nolearn#140]
So if i'm not mistaken, the default linearity in lasagne is rectified-linear,
for a regression problem I had the impression the activation function in the last layer,
should be the linear activation function. 

Would the following be a correct architecture for regression ? 

(apologies for posting in issues, would lasagne google-group be better ? )
 
```python
from lasagne.nonlinearities import linear
...

layers = [
     (InputLayer,{'name': 'input', 'shape': (None, X.shape[1])}),
     (DenseLayer, {'num_units': 500}),
     (DropoutLayer, {'name':'dropout4', 'p':0.5}),
     (DenseLayer, {'num_units': 500}),
     (DropoutLayer, {'name':'dropout5', 'p':0.5}),
     # the output layer
     (DenseLayer, {'num_units': 1, 'nonlinearity': linear}), 
  ]

net0 = NeuralNet( layers=layers0,
            max_epochs=3000,
            train_split=TrainSplit(eval_size=0.25),
            verbose=2,
            regression=True,
            update=adadelta)
```

**Comment by hiendang** [comment]
It should be identity function, not linear:
```python
from lasagne.nonlinearities import identity
```

**Comment by cbonnett** [comment]
In Lasagne the linear function is seems to be equal to the identity function

In [2]: from lasagne.nonlinearities import linear
In [3]: from lasagne.nonlinearities import identity
In [4]: identity == linear
Out[4]: True

**Comment by dnouri** [comment]
Looks good to me!
