### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by dmilush** [dnouri/nolearn#141]
I have installed the latest version from git.
However, I get the following import error
----> 1 from nolearn.lasagne import objective
ImportError: cannot import name objective

**Comment by dnouri** [comment]
Looks like installing from Git didn't work.  How did you install it?  Please include commands and relevant output.

**Comment by dmilush** [comment]
sudo pip install -r https://raw.githubusercontent.com/dnouri/nolearn/master/requirements.txt 
Cloning https://github.com/Theano/Theano.git (to 36d1eca8) to /tmp/pip_build_root/Theano
  Could not find a tag or branch '36d1eca8', assuming commit.
  Running setup.py (path:/tmp/pip_build_root/Theano/setup.py) egg_info for package Theano
    
    warning: manifest_maker: MANIFEST.in, line 8: 'recursive-include' expects <dir> <pattern1> <pattern2> ...
    
  Requested Theano==0.8.git from git+https://github.com/Theano/Theano.git@36d1eca8 (from -r https://raw.githubusercontent.com/dnouri/nolearn/master/requirements.txt (line 6)), but installing version 0.7.0
Downloading/unpacking Lasagne==0.1.git from git+https://github.com/Lasagne/Lasagne.git@30ea8e5 (from -r https://raw.githubusercontent.com/dnouri/nolearn/master/requirements.txt (line 7))
  Cloning https://github.com/Lasagne/Lasagne.git (to 30ea8e5) to /tmp/pip_build_root/Lasagne
  Could not find a tag or branch '30ea8e5', assuming commit.
  Running setup.py (path:/tmp/pip_build_root/Lasagne/setup.py) egg_info for package Lasagne
    
  Requested Lasagne==0.1.git from git+https://github.com/Lasagne/Lasagne.git@30ea8e5 (from -r https://raw.githubusercontent.com/dnouri/nolearn/master/requirements.txt (line 7)), but installing version 0.1

Installing collected packages: Theano, Lasagne
  Found existing installation: Theano 0.7.0
    Can't uninstall 'Theano'. No files were found to uninstall.
  Running setup.py install for Theano
    changing mode of build/scripts-2.7/theano-cache from 644 to 755
    changing mode of build/scripts-2.7/theano-nose from 644 to 755
    changing mode of build/scripts-2.7/theano-test from 644 to 755
    
    warning: manifest_maker: MANIFEST.in, line 8: 'recursive-include' expects <dir> <pattern1> <pattern2> ...
    
    changing mode of /usr/local/bin/theano-nose to 755
    changing mode of /usr/local/bin/theano-test to 755
    changing mode of /usr/local/bin/theano-cache to 755
  Found existing installation: Lasagne 0.1.dev0
    Can't uninstall 'Lasagne'. No files were found to uninstall.
  Running setup.py install for Lasagne
    
Successfully installed Theano Lasagne
Cleaning up...

sudo pip install git+https://github.com/dnouri/nolearn.git@master
Downloading/unpacking git+https://github.com/dnouri/nolearn.git@master
  Cloning https://github.com/dnouri/nolearn.git (to master) to /tmp/pip-CYFtcl-build
  Running setup.py (path:/tmp/pip-CYFtcl-build/setup.py) egg_info for package from git+https://github.com/dnouri/nolearn.git@master
    /usr/local/lib/python2.7/dist-packages/setuptools-18.1-py2.7.egg/setuptools/dist.py:285: UserWarning: Normalizing '0.6adev' to '0.6a0.dev0'
    
  Requirement already satisfied (use --upgrade to upgrade): nolearn==0.6a0.dev0 from git+https://github.com/dnouri/nolearn.git@master in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): joblib in /usr/local/lib/python2.7/dist-packages (from nolearn==0.6a0.dev0)
Requirement already satisfied (use --upgrade to upgrade): matplotlib in /usr/local/lib/python2.7/dist-packages (from nolearn==0.6a0.dev0)
Requirement already satisfied (use --upgrade to upgrade): scikit-learn in /usr/local/lib/python2.7/dist-packages (from nolearn==0.6a0.dev0)
Requirement already satisfied (use --upgrade to upgrade): tabulate in /usr/local/lib/python2.7/dist-packages (from nolearn==0.6a0.dev0)
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.6 in /usr/local/lib/python2.7/dist-packages (from matplotlib->nolearn==0.6a0.dev0)
Requirement already satisfied (use --upgrade to upgrade): six>=1.4 in /usr/local/lib/python2.7/dist-packages (from matplotlib->nolearn==0.6a0.dev0)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /usr/local/lib/python2.7/dist-packages (from matplotlib->nolearn==0.6a0.dev0)
Requirement already satisfied (use --upgrade to upgrade): pytz in /usr/local/lib/python2.7/dist-packages (from matplotlib->nolearn==0.6a0.dev0)
Requirement already satisfied (use --upgrade to upgrade): pyparsing>=1.5.6 in /usr/local/lib/python2.7/dist-packages (from matplotlib->nolearn==0.6a0.dev0)
Requirement already satisfied (use --upgrade to upgrade): nose>=0.11.1 in /usr/local/lib/python2.7/dist-packages (from matplotlib->nolearn==0.6a0.dev0)
Requirement already satisfied (use --upgrade to upgrade): mock in /home/dimiter/.local/lib/python2.7/site-packages (from matplotlib->nolearn==0.6a0.dev0)
Cleaning up...

**Comment by dnouri** [comment]
Thanks.  I've again updated installation instructions in 4d718fb77ab286cca8605d3cd44b13f5e2c9df53.  Please try again.

**Comment by dmilush** [comment]
Thanks. I still can't get 0.7. I also tried on another machine that did not have nolearn with the same result.
 Requested nolearn==0.7.git from git+https://github.com/dnouri/nolearn.git@master, but installing version 0.6a0.dev0
I

**Comment by dnouri** [comment]
You can ignore that.  The 0.7 is just a trick to have it download and install the package every time.  Let me know if things are working now.

**Comment by dmilush** [comment]
Thanks for your help! Although it installs now, there seems to be some problem with lasagne integration.
Whenever I try to import anything from  nolearn.lasagne  (e.g. from nolearn.lasagne import NeuralNet),
I get  an Import Error. Something like:
ImportError                               Traceback (most recent call last)
<ipython-input-1-f81637438a2c> in <module>()
----> 1 from nolearn.lasagne import NeuralNet

/usr/local/lib/python2.7/dist-packages/nolearn/lasagne/__init__.py in <module>()
      4     SaveWeights,
      5     )
----> 6 from .base import (
      7     BatchIterator,
      8     objective,

/usr/local/lib/python2.7/dist-packages/nolearn/lasagne/base.py in <module>()
     10 import pdb
     11 
---> 12 from lasagne.layers import get_output
     13 from lasagne.layers import InputLayer
     14 from lasagne.objectives import aggregate
The funny thing is it works on my laptop, where I had no previous installation.

**Comment by dnouri** [comment]
Looks like a too old version of Lasagne.  :-(

I'm surprised the installation instructions still seem to not get a
recent enough version?  There's something funny going on.

**Comment by dmilush** [comment]
Yep, that was indeed the problem. The installation instructions only work if you don't have an older (0.1) version of Lasagne. If you do, you need to manually uninstall Lasagne first. Then the instructions will work. Thanks you very much for the help!
