### ISSUE TITLE
ImportError: cannot import name mse

### ISSUE THREAD

**Issue by deTrident** [dnouri/nolearn#142]
```python
from lasagna.objectives import mse 
ImportError: cannot import name mse
```
solution: As the latest Lasagne, change the file "dist-packages/nolearn/lasagne.py" [from lasagna.objectives import mse] to [from lasagne.objectives import squared_error]

**Comment by dnouri** [comment]
Not sure which version of Lasagne and nolearn you're using, but this error shouldn't occur if you [follow the installation instructions](https://github.com/dnouri/nolearn#installation).

**Comment by zbyte64** [comment]
Strange, I installed the version from requirements but still get this issue. I looked up the commit version mentioned for Lasagne but I don't see mse defined:

https://github.com/Lasagne/Lasagne/blob/b6f1250eb95b6b036cd348a37dbfc4dbf84d8a67/lasagne/objectives.py

**Comment by avinash2692** [comment]
The latest version of Lasange renames mse as `squared_error`. PLease check this link for further clarification http://lasagne.readthedocs.org/en/latest/modules/objectives.html#lasagne.objectives.squared_error

possible solution : Update the requirements.txt line 7 
`-e git+https://github.com/Lasagne/Lasagne.git@b6f1250e#egg=Lasagne==0.2.git` for the latest version of lasange

**Comment by dnouri** [comment]
> Strange, I installed the version from requirements but still get this issue. I looked up the commit version mentioned for Lasagne but I don't see mse defined

Yes, Lasagne now has `squared_error`, which is what [nolearn uses](https://github.com/dnouri/nolearn/blob/924cde6f3fa83f73535dfbf7915992388ba1cab3/nolearn/lasagne/base.py#L18).

**Comment by avinash2692** [comment]
Got It ! I just made the change manually in my local files, but I think I'll pull the latest from nolearn .. Thanks !

**Comment by CraveInfinity** [comment]
I have upgraded both the modules but nolearn is still reluctant to use squared_error. Fixed Lasagne though.
