### ISSUE TITLE
Consider splitting up batch_iterator for test and train

### ISSUE THREAD

**Issue by cancan101** [dnouri/nolearn#15]
Rather than requiring the user to use the same class for the `batch_iterator` [used for train and test](https://github.com/dnouri/nolearn/blob/f3bfe77ce23047a662743ed08d3a910408d39dc0/nolearn/lasagne.py#L180), consider [adding a `batch_iterator_test`](https://github.com/dnouri/nolearn/blob/master/nolearn/lasagne.py#L76).

This would simply the `FlipBatchIterator` in the blog post and allow just using the standard `BatchIterator` for the `batch_iterator_test`.

**Comment by dnouri** [comment]
Liked the idea!
