### ISSUE TITLE
Consider fixing the necessity to do 'fit' prior to 'predict' after 'load_weights'

### ISSUE THREAD

**Issue by DediGadot** [dnouri/nolearn#16]
Currently, after re-loading the weights of a pre-trained network, you have to do nn.fit prior to nn.predict. Consider fixing that for better usability.

Thanks,
David

**Comment by dnouri** [comment]
With the latest version, there's now a dedicated `initialize()` method.  Call it before you call `nn.predict`.  Please re-open if you believe the issue still exists.
