### ISSUE TITLE
Allow references to other layers in the layer kwargs

### ISSUE THREAD

**Issue by DanChianucci** [dnouri/nolearn#174]
Some layers in lasagne are able to reference other layers in the network.  

For example, you can share the weights from one layer to another by providing W=otherLayer.W as a kwarg to the new layer.  The NeuralNet initialize_layers() takes care of parameter sharing for W, and b attributes, however I do not see a way to do this for other parameters.

Specifically, I would like to be able to provide a previous layer as the layer attribute of an InverseLayer.

**Comment by BenjaminBossan** [comment]
It is now possible to initialize your layers as you would in Lasagne. Then you provide the last (output) layer to the `layers` argument of `NeuralNet`. This should make it easier to cover your case.

**Comment by dnouri** [comment]
Thanks, @BenjaminBossan.  Here's another example of using the vanilla Lasagne way to define layers:

```python
layer = InputLayer(shape=(None, 1, 28, 28))
layer = Conv2DLayer(layer, filter_size=5, num_filters=8)
layer = MaxPool2DLayer(layer, pool_size=2)
layer = Conv2DLayer(layer, filter_size=5, num_filters=8)
layer = MaxPool2DLayer(layer, pool_size=2)
layer = DenseLayer(layer, num_units=128)
layer = DenseLayer(layer, nonlinearity=softmax, num_units=10)

net = NeuralNet(
    layer,
    update=nesterov_momentum,
    update_learning_rate=0.01,
    update_momentum=0.9,
    )
```
