### ISSUE TITLE
Consider moving EarlyStopping into nolearn

### ISSUE THREAD

**Issue by cancan101** [dnouri/nolearn#18]
Consider moving [EarlyStopping](https://github.com/dnouri/kfkd-tutorial/blob/f6010a9feefd9af01e0afaeba1927a488ec90846/kfkd.py#L156) to nolearn.

**Comment by felixlaumon** [comment]
I think It will be a good idea to add a `threshold` too, so it won't get stuck on minor improvement.

**Comment by cancan101** [comment]
We also want to make sure to deal with the issues I outlined in #32.

**Comment by cancan101** [comment]
This is what I am using now:
```python
class EarlyStopping(object):
    def __init__(self, patience=100):
        self.patience = patience
        self.best_valid = np.inf
        self.best_valid_epoch = 0
        self.best_weights = None

    def __call__(self, nn, train_history):
        current_valid = train_history[-1]['valid_loss']
        current_epoch = train_history[-1]['epoch']
        if current_valid < self.best_valid:
            self.best_valid = current_valid
            self.best_valid_epoch = current_epoch
            self.best_weights = [w.get_value() for w in nn.get_all_params()]
        elif self.best_valid_epoch + self.patience < current_epoch:
            if nn.verbose:
                print("Early stopping.")
                print("Best valid loss was {:.6f} at epoch {}.".format(
                    self.best_valid, self.best_valid_epoch))
            nn.load_weights_from(self.best_weights)
            if nn.verbose:
                print("Weights set.")
            raise StopIteration()

    def load_best_weights(self, nn, train_history):
        nn.load_weights_from(self.best_weights)
```

**Comment by paipai880429** [comment]
@cancan101, you are definitely an expert in this field. Would you mind taking a minute look issue 46: https://github.com/dnouri/nolearn/issues/46 ? Thank you.

**Comment by ternaus** [comment]
I am getting an error:

 Loading weights from a list of parameter values is no longer supported.  Please send me something like the return value of 'net.get_all_param_values()' instead.

**Comment by dnouri** [comment]
@ternaus Change this line:

`self.best_weights = [w.get_value() for w in nn.get_all_params()]`

to

`self.best_weights = nn.get_all_params_values()`

**Comment by cancan101** [comment]
Related to #155.

**Comment by dnouri** [comment]
EarlyStopping is [part of nolearn-utils](https://github.com/felixlaumon/nolearn_utils/blob/master/nolearn_utils/hooks.py).  Suggest you use the implementation from there.
