### ISSUE TITLE
MemoryError 

### ISSUE THREAD

**Issue by NetzerEitan** [dnouri/nolearn#180]
Hi
I am trying to train a net.
Even after I am setting the batch size to be small 
batch_iterator_train=BatchIterator(batch_size=8)

The size of my training set is to big.
I can only use about 200 samples
Training_X = float32((np.load('Training_X.npy')[0:200,:,:,:]))

More than that and get a MemoryError.

Thanks in Advance
Eitan

**Comment by BenjaminBossan** [comment]
MemoryErrors should usually not depend on the size of the training set but on the batch size. Are you getting a GPU MemoryError? More code would help in diagnosing the problem.

**Comment by dnouri** [comment]
Closing for lack of feedback.

OP probably wants to write a batch iterator to load chunks of data during iteration (e.g. by passing a list of filenames as X).  Or they might want to look into using HDF5.
