### ISSUE TITLE
Trying to use Lasagne **tags when creating a Neural Network

### ISSUE THREAD

**Issue by caleytown** [dnouri/nolearn#181]
I'm currently trying to set the "trainable=False" on the base layer class for the neural network I am setting up using Lasagne (http://lasagne.readthedocs.org/en/latest/modules/layers/base.html).  When I try and pass it as a parameter when I setup my neural net, I get the following error:

TypeError: Failed to instantiate <class 'lasagne.layers.conv.Conv2DLayer'> with args {'incoming': <lasagne.layers.input.InputLayer object at 0x110b05c90>, 'name': 'conv2d1', 'trainable': False, 'filter_size': 9, 'pad': 'valid', 'num_filters': 16}.
Maybe parameter names have changed?

It appears that when nolearn constructs the neural network in lasagne, it's not passing the tags correctly.  Is there something I am missing?

The snippet of my code that is failing is:

layers = [
    (InputLayer, {'shape': (None, X.shape[1], X.shape[2], X.shape[3])}),
    (Conv2DLayerFast, {'num_filters': conv_num_filters, 'filter_size': filter_size1, 'pad': pad_in,'trainable': False}),
]

Thanks

**Comment by BenjaminBossan** [comment]
Are you able to instantiate the layers Lasagne style?
```
input = InputLayer(shape=...)
conv1 = Conv2DLayerFast(input, ..., trainable=True)
...
```

**Comment by caleytown** [comment]
I am, I was trying to do it using NoLearn.  I was able to get it working by modifying the layers after no learn ran its initialization function.  Seems like I should be able to do this on construction of the NN using no learn....  Bug?

ae.initialize()
for layerName in ae.layers_:
    if isinstance(ae.layers_[layerName],Conv2DLayerSlow):
        ae.layers_[layerName].W = ae.layers_[layerName].add_param(ae.layers_[layerName].W,ae.layers_[layerName].W.container.data.shape, trainable=False)
        ae.layers_[layerName].b = ae.layers_[layerName].add_param(ae.layers_[layerName].b,ae.layers_[layerName].b.container.data.shape, trainable=False)

**Comment by BenjaminBossan** [comment]
Okay, thanks, so this may be a bug. I will look into it when I have time.

**Comment by BenjaminBossan** [comment]
I just tried and it seems you cannot pass the `trainable` parameter to a Lasagne layer but instead have to pass it to each parameter individually. This raises a TypeError:

    from lasagne import layers
    l = layers.InputLayer(shape=(10, 10))
    l = layers.DenseLayer(l, num_units=10, trainable=True)

Instead this seems to work:

    l = layers.InputLayer(shape=(10, 10))
    l = layers.DenseLayer(l, num_units=10)
    l.add_param(l.W, l.W.get_value().shape, trainable=False)
    layers.get_all_params(l, trainable=False)  # returns [W]

Maybe there is a more elegant way. Anyway, this does not seem to be a nolearn bug.
