### ISSUE TITLE
 AttributeError: 'DenseLayer' object has no attribute 'get_output_shape'

### ISSUE THREAD

**Issue by Vikrant79** [dnouri/nolearn#184]
Hi,
I am getting the below error while using lasange and nolearn. Earlier I was getting "can not import mse error" which I fixed by manually editing the lasagne.py file and changed mse to squared_error. That issue got resolved. Do you have any quick fix for the below error?
I have tried installing and uninstalling the lasange and nolearn multiple times but error is not going. I can see after every unistall and install lasagne.py file content is not changing. is the older version of nolearn still creating problem. How to fix. Please guide.

```
AttributeError                            Traceback (most recent call last)
<ipython-input-298-767460c55f9b> in <module>()
----> 1 net0.fit(X, y)

C:\Users\Admin\Anaconda\lib\site-packages\nolearn\lasagne.pyc in fit(self, X, y)
    138             out = self._output_layer = self.initialize_layers()
    139         if self.verbose:
--> 140             self._print_layer_info(self.get_all_layers())
    141 
    142         iter_funcs = self._create_iter_funcs(

C:\Users\Admin\Anaconda\lib\site-packages\nolearn\lasagne.pyc in _print_layer_info(self, layers)
    374     def _print_layer_info(self, layers):
    375         for layer in layers:
--> 376             output_shape = layer.get_output_shape()
    377             print("  {:<18}\t{:<20}\tproduces {:>7} outputs".format(
    378                 layer.__class__.__name__,

AttributeError: 'DenseLayer' object has no attribute 'get_output_shape'
```

**Comment by BenjaminBossan** [comment]
Hard to tell from the code, but it seems that you have a very old nolearn version installed (and presumably Lasagne too). How did you install them? My preferred method is directly from github, as other sources (pip) often lag behind.

**Comment by dnouri** [comment]
Agree that this looks like a very old version of nolearn.  Please take a look at the [installation instructions](https://github.com/dnouri/nolearn#installation) and at my [Anaconda related comment here](https://github.com/dnouri/nolearn/issues/234#issuecomment-201511352).
