### ISSUE TITLE
Doubt in Using CNN Pre-Trained Weights using Lasagne

### ISSUE THREAD

**Issue by avisekiit** [dnouri/nolearn#188]
Hi All,

I am implementing a CNN following the Lasagne tutorial of Daniel. I am facing a confusion while using pre-trained weights. Specifically, I have initially trained a neural network, say, net1

    net1.fit(X1,y1)
    joblib.load(net1,'net1.pkl') # saves the entire model

Next, I am trying to initiate my second neural net with the weights learnt in net1.For this, I do:

    pre_trained_net=joblib.load('net1.pkl') # to load the net1 model
    net2=clone(pre_trained_net)
    net2.load_params_from(pre_trained_net)
    net2.fix(X2,y2)

###################

My doubts are:
a) Is my implementation correct? Because, even when I am training the net2 I am getting the message ("
UserWarning: The uniform initializer no longer uses Glorot et al.'s approach to determine the bounds, but defaults to the range (-0.01, 0.01) instead."

):: Usually, I get this message when I initialize the network from scratch with random weights

b) I trained a net3 with random initialisation with same dataset (X2,y2). The train and validation error rates of net2 and net3 are exactly same. This observation is amplifying my doubt.

Keenly waiting for expert suggestions.

Thanks,
Avisek

**Comment by BenjaminBossan** [comment]
Hi Avisek,

Do you have a specific reason to use joblib for saving the model? Usually, I would use the integrated `net1.save_params_to('some_file')` method for saving and `net2.load_params_from('some_file')` method for loading the weights again. Set `verbose` to 1 to see some feedback before loading.

To test whether the loading worked, you should initialize a net, check the net's score on a fixed dataset (score0), then train, check the score again (score1). Then load weights to a new net with the same settings and check scores again (score2). You should find that score0 != score1 == score2, in which case all worked fine.

Hopefully, that helps.

**Comment by avisekiit** [comment]
Hi Benjamin,

Thanks for the explanation. I am facing a doubt while using
net2.load_params_from() method.

My net1 (or juntingnet) definition looks like this:

class *AdjustVariable(*object):
    def __init__(self, name, start=0.03, stop=0.001):
        self.name = name
        self.start, self.stop = start, stop
        self.ls = None

    def __call__(self, nn, train_history):
        if self.ls is None:
            self.ls = np.linspace(self.start, self.stop, nn.max_epochs)

        epoch = train_history[-1]['epoch']
        new_value = float32(self.ls[epoch - 1])
        getattr(nn, self.name).set_value(new_value)

class *FlipBatchIterator*(BatchIterator):
    def transform(self, Xb, yb):
        Xb, yb = super(FlipBatchIterator, self).transform(Xb, yb)

        # Flip half of the images in this batch at random:
        bs = Xb.shape[0]
        indices = np.random.choice(bs, bs / 2, replace=False)
        Xb[indices] = Xb[indices, :, :, ::-1]
        tmp =  yb[indices].reshape(bs/2,1,map_size,map_size)
        mirror = tmp[ :,:,:, ::-1]
        yb[indices] =  mirror.reshape(bs/2,map_size*map_size)
        return Xb, yb

juntingnet = NeuralNet(
    layers=[
        ('input', layers.InputLayer),
        ('conv1', layers.Conv2DLayer),
        ('pool1', layers.MaxPool2DLayer),
        ('conv2', layers.Conv2DLayer),
        ('pool2', layers.MaxPool2DLayer),
        ('conv3', layers.Conv2DLayer),
        ('pool3', layers.MaxPool2DLayer),
        ('hidden4', layers.DenseLayer),
        ('maxout6',layers.FeaturePoolLayer),
        ('output', layers.DenseLayer),
        ],
    input_shape=(None, 3, image_size, image_size),
    conv1_num_filters=map_size, conv1_filter_size=(5, 5),
pool1_pool_size=(2, 2),
    conv2_num_filters=64, conv2_filter_size=(3, 3), pool2_pool_size=(2, 2),
    conv3_num_filters=64, conv3_filter_size=(3, 3), pool3_pool_size=(2, 2),
    hidden4_num_units=map_size*map_size*2,

maxout6_pool_size=2,output_num_units=map_size*map_size,output_nonlinearity=None,

    update_learning_rate=theano.shared(float32(0.05)),
    update_momentum=theano.shared(float32(0.9)),

    regression=True,

    on_epoch_finished=[
        AdjustVariable('update_learning_rate', start=0.05, stop=0.0001),
        AdjustVariable('update_momentum', start=0.9, stop=0.999),
        ],
    batch_iterator_train=BatchIterator(batch_size=128),
    max_epochs=2,
    verbose=1,
    )
juntingnet.fit(X, y)
juntingnet.save_params_to('juntingsave.pkl')
-----------------------------


################  INITIALIZE net2 with pre-trained juntingnet##############

Should i initialise net2 exactly as i did juntingnet. I mean, is there any
need to define the FlipBatchIterator and AdjustVariable classes all over
again ?

Else, how should I initialize net2 so that I can just hold the skeleton
structure of juntingnet and then load the parameters.
I am aware of a clone() method, but not sure about how to use it exactly.

Your solution will help me in two ways:
1) using pretrained weights I can initiate another network
2) load a trained model for predict() method

Awaiting your kind response.

Thanks,
Avisek

**Comment by BenjaminBossan** [comment]
If you want your net2 to do exactly the same thing as juntingnet, you should initialize it exactly the same way: `net2 = NeuralNet(<same as before>)`. The `load_params_from` method only loads the layers' weights and biases, so if the other parameters should be the same, you have to tell the net so.
If, however, you don't want to use, say, `AdjustVariable`, you may leave it out.

In general, the classes only have to be defined once.
