### ISSUE TITLE
Append git hash to version when installing from git

### ISSUE THREAD

**Issue by cancan101** [dnouri/nolearn#190]
Given the infrequency of pypi releases many users install nolearn from git rather than from pypi. Because of this, the version string does not full capture the installed version (i.e. the git hash). I would suggest adding the commit hash to the version string when installing from git. This would be consistent with [what Theano does](https://github.com/Theano/Theano/blob/149d008d528277988867089cb607105e706910c4/setup.py#L134-L143).

**Comment by dnouri** [comment]
Not very useful as established here: https://github.com/Lasagne/Lasagne/issues/574#issuecomment-171392813
