### ISSUE TITLE
Update Nolearn PyPi package

### ISSUE THREAD

**Issue by cancan101** [dnouri/nolearn#192]
It has been ~12 months since the last release even though there has been a lot of work on the repos.

**Comment by dnouri** [comment]
We can roll another release once Lasagne releases.

**Comment by dnouri** [comment]
Lasagne hasn't released.  I released a new nolearn anyway: See https://pypi.python.org/pypi/nolearn/0.6.0/ and https://github.com/dnouri/nolearn/releases/tag/0.6.0
