### ISSUE TITLE
TensorType issue

### ISSUE THREAD

**Issue by lindazy** [dnouri/nolearn#200]
Hey,
I'm trying to train a network where some of the features are probabilities (0 < x < 1).
I get an error:

TypeError: ('Bad input argument to theano function at index 1(0-based)', 'TensorType(int32, vector) cannot store a value of dtype float32 without risking loss of precision. If you do not mind this loss, you can: 1) explicitly cast your data to int32, or 2) set "allow_input_downcast=True" when calling "function".', array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.], dtype=float32))

Since it's the difference between a float and int, and I need the input to be a float, input downcasting isn't really a solution. However, I'm not sure how to specify that I want the X to be of type float. I looked in lasagne/base.py, and see that the "X_tensor_type" parameter has been removed because it is unnecessary, however there is no other way to specify the type of the X tensor?

Thanks!
Linda

**Comment by BenjaminBossan** [comment]
Hi Linda, could you show the code that produces the error?

**Comment by lindazy** [comment]
This is the main part:
        print("Loading data...")
        X_train, y_train, X_test, y_test = load_data()
        data_shape = [None]
        for x in X_train.shape[1:]:
                data_shape.append(x)
        data_shape = tuple(data_shape)
        print('shape', data_shape)

        network = build_nolearn_dnn(depth=2, width=200, drop_hidden=0.5, data_shape=data_shape, max_epochs=500)
        network.fit(X_train, y_train)

def build_nolearn_cnn(data_shape=(None, 100), filter_size = (20,4), epochs=200):
        layers=[
                (lasagne.layers.InputLayer, {'shape':data_shape}),
                (lasagne.layers.Conv2DLayer, {'num_filters':32, 'filter_size':filter_size, 'nonlinearity':lasagne.nonlinearities.rectify}),
                (lasagne.layers.DropoutLayer, {'p':0.5}),
                (lasagne.layers.DenseLayer, {'num_units':2, 'nonlinearity':lasagne.nonlinearities.softmax})
        ]

        network = NeuralNet(
                layers=layers,
                update=lasagne.updates.nesterov_momentum,
                update_learning_rate=0.01,
                update_momentum=0.9,

                max_epochs=epochs,
                verbose=1,
        )
        return network


NOTE, this works when I cast the data as int32. But when I do that, my floats turn into 0. I'm looking for an option that allows me to specify the tensortype, basically.

**Comment by BenjaminBossan** [comment]
What data causes the trouble, X or y? What are their dtypes? And do you want to train a classifier or regressor?

Also, it would help if you showed the code for `build_nolearn_dnn`.

**Comment by lindazy** [comment]
Oops, I guess I showed the wrong code!
    def build_nolearn_dnn(depth=2, width=200, drop_input=0, drop_hidden=.5, data_shape=(None, 100), max_epochs=10):
        layers=[(lasagne.layers.InputLayer, {'shape':data_shape}),]
        for _ in range(depth):
                layers.append((lasagne.layers.DenseLayer, {'num_units':width, 'nonlinearity':lasagne.nonlinearities.rectify}))
                if drop_hidden > 0:
                        layers.append((lasagne.layers.DropoutLayer, {'p':drop_hidden}))

        layers.append((lasagne.layers.DenseLayer, {'num_units':2, 'nonlinearity':lasagne.nonlinearities.softmax}))

        network = NeuralNet(
                layers=layers,
                update=lasagne.updates.nesterov_momentum,
                update_learning_rate=0.01,
                update_momentum=0.9,

                max_epochs=max_epochs,
                verbose=1,
        )
        return network

The X causes the trouble. The type is float, but I want it to stay a float type.

**Comment by BenjaminBossan** [comment]
Hi, for me your code seems to work, though of course I don't have your data. Could you test whether this slightly modified snippet still throws the error:

```
import numpy as np
import lasagne
from nolearn.lasagne import NeuralNet

def build_nolearn_dnn(depth=2, width=200, drop_input=0, drop_hidden=.5, data_shape=(None, 100), max_epochs=10):
    layers=[(lasagne.layers.InputLayer, {'shape':data_shape}),]
    for _ in range(depth):
            layers.append((lasagne.layers.DenseLayer, {'num_units':width, 'nonlinearity':lasagne.nonlinearities.rectify}))
            if drop_hidden > 0:
                    layers.append((lasagne.layers.DropoutLayer, {'p':drop_hidden}))

    layers.append((lasagne.layers.DenseLayer, {'num_units':2, 'nonlinearity':lasagne.nonlinearities.softmax}))

    network = NeuralNet(
            layers=layers,
            update=lasagne.updates.nesterov_momentum,
            update_learning_rate=0.01,
            update_momentum=0.9,

            max_epochs=max_epochs,
            verbose=1,
    )
    return network

print("Loading data...")
X_train, y_train = np.random.rand(1000, 20).astype(np.float32), np.random.randint(0, 10, (1000)).astype(np.int32)
data_shape = [None]
for x in X_train.shape[1:]:
    data_shape.append(x)
data_shape = tuple(data_shape)
print('shape', data_shape)
network = build_nolearn_dnn(depth=2, width=200, drop_hidden=0.5, data_shape=data_shape, max_epochs=10)
network.fit(X_train, y_train)

```

**Comment by lindazy** [comment]
Hmm, running exactly that code gives me this error:
Traceback (most recent call last):
  File "/home/zhanl10/asa-project/venv3/src/theano/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
ValueError: y_i value out of bounds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 33, in <module>
    network.fit(X_train, y_train)
  File "/home/zhanl10/asa-project/venv3/lib/python3.4/site-packages/nolearn/lasagne/base.py", line 509, in fit
    self.train_loop(X, y, epochs=epochs)
  File "/home/zhanl10/asa-project/venv3/lib/python3.4/site-packages/nolearn/lasagne/base.py", line 563, in train_loop
    self.train_iter_, Xb, yb)
  File "/home/zhanl10/asa-project/venv3/lib/python3.4/site-packages/nolearn/lasagne/base.py", line 620, in apply_batch_func
    return func(Xb) if yb is None else func(Xb, yb)
  File "/home/zhanl10/asa-project/venv3/src/theano/theano/compile/function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/zhanl10/asa-project/venv3/src/theano/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/zhanl10/asa-project/venv3/lib/python3.4/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/zhanl10/asa-project/venv3/src/theano/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
ValueError: y_i value out of bounds
Apply node that caused the error: CrossentropySoftmaxArgmax1HotWithBias(Dot22.0, dense5.b, y_batch)
Toposort index: 27
Inputs types: [TensorType(float64, matrix), TensorType(float64, vector), TensorType(int32, vector)]
Inputs shapes: [(128, 2), (2,), (128,)]
Inputs strides: [(16, 8), (8,), (4,)]
Inputs values: ['not shown', array([ 0.,  0.]), 'not shown']
Outputs clients: [[Sum{acc_dtype=float64}(CrossentropySoftmaxArgmax1HotWithBias.0)], [CrossentropySoftmax1HotWithBiasDx(Elemwise{Inv}[(0, 0)].0, CrossentropySoftmaxArgmax1HotWithBias.1, y_batch)], []]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

**Comment by lindazy** [comment]
Hmm, that's really strange.
That code (with y_train = np.random.randint(0, 10, (1000)).astype(np.int32)) works for me.
