### ISSUE TITLE
Spatial transformer (layer that takes another layer that is not "incoming")

### ISSUE THREAD

**Issue by christopher-beckham** [dnouri/nolearn#205]
Hi,

I am trying to train a network with a spatial transformer and the class needs to be passed the layer that computes the transform params, e.g the parameter "localization_network":

http://lasagne.readthedocs.org/en/latest/modules/layers/special.html

Is this possible with nolearn?

I'm aware of how to make a layer in nolearn take multiple input layers, but I'm not sure how to go about passing a layer that isn't under the parameter "incoming". Would I have to modify some of the code in base.py myself?

Cheers

**Comment by dnouri** [comment]
@christopher-beckham You can pass an ordinary Lasagne network as the first parameter of a `NeuralNet` since a while ago.  Here's an example:

```python
layer = InputLayer(shape=(None, 1, 28, 28))
layer = Conv2DLayer(layer, filter_size=5, num_filters=8)
layer = MaxPool2DLayer(layer, pool_size=2)
layer = Conv2DLayer(layer, filter_size=5, num_filters=8)
layer = MaxPool2DLayer(layer, pool_size=2)
layer = DenseLayer(layer, num_units=128)
layer = DenseLayer(layer, nonlinearity=softmax, num_units=10)

net = NeuralNet(
    layer,
    update=nesterov_momentum,
    update_learning_rate=0.01,
    update_momentum=0.9,
    )
```
