### ISSUE TITLE
Error -- AttributeError: 'module' object has no attribute 'Param'

### ISSUE THREAD

**Issue by yilisg** [dnouri/nolearn#206]
Code worked on Ubuntu and but got an error when I try it on a Windows box. It could be an installation problem but I don't seem to be able to pull v 0.7 off github (but I am pretty sure I have the latest commit).

`pip install --upgrade --no-deps git+https://github.com/dnouri/nolearn.git@master#egg=nolearn==0.7.git`

But I am still seeing 
```
Installing collected packages: nolearn
  Found existing installation: nolearn 0.6a0.dev0
    Uninstalling nolearn-0.6a0.dev0:
      Successfully uninstalled nolearn-0.6a0.dev0
  Running setup.py install for nolearn ... done
Successfully installed nolearn-0.6a0.dev0
```

I've also tested other Theano / Lasagne code and they seem to be fine (using GPU).
_Using gpu device 0: GeForce GTX 980 Ti (CNMeM is disabled)_

**Traceback**
  ```
File "<ipython-input-1-73edbf7c2382>", line 108, in <module>
    net1.fit(train, train_y)

  File "C:\Anaconda2\lib\site-packages\nolearn\lasagne\base.py", line 518, in fit
    self.initialize()

  File "C:\Anaconda2\lib\site-packages\nolearn\lasagne\base.py", line 359, in initialize
    self.y_tensor_type,

  File "C:\Anaconda2\lib\site-packages\nolearn\lasagne\base.py", line 489, in _create_iter_funcs
    for input_layer in input_layers]

AttributeError: 'module' object has no attribute 'Param'
```

Other Module Versions
Theano-0.8.0.dev0-py2.7.egg-info
Lasagne-0.2.dev1-py2.7.egg-info

**Comment by dnouri** [comment]
Try again with the latest version of nolearn.  Open this issue again if the problem isn't resolved.

**Comment by yilisg** [comment]
Resolved. Thanks Daniel.
