### ISSUE TITLE
NotImplementedError when loading parameters.

### ISSUE THREAD

**Issue by gunsl1nger** [dnouri/nolearn#211]
Hello, I just updated nolearn and when I tried to load parameters to my network the following was raised:

Traceback (most recent call last):
  File "/home/...py", line 339, in compression_model
    net.load_params_from(parameters)
  File "/usr/local/lib/python2.7/dist-packages/nolearn/lasagne/base.py", line 694, in load_params_from
    self.initialize()
  File "/usr/local/lib/python2.7/dist-packages/nolearn/lasagne/base.py", line 359, in initialize
    self.y_tensor_type,
  File "/usr/local/lib/python2.7/dist-packages/nolearn/lasagne/base.py", line 496, in _create_iter_funcs
    allow_input_downcast=True,
  File "/home/gunslinger/src/theano/theano/compile/function.py", line 297, in function
    "In() instances and tuple inputs trigger the old "
NotImplementedError: In() instances and tuple inputs trigger the old semantics, which disallow using updates and givens

Is this common? Why is everybody calm am I the only one that can't compile his nolearn models?

To keep this short I will paste code if needed.

**Comment by gunsl1nger** [comment]
Sorry for double posting, here's another error: 

nn_classifier.fit(features, transformed_phonemes)
  File "/usr/local/lib/python2.7/dist-packages/nolearn/lasagne/base.py", line 518, in fit
    self.initialize()
  File "/usr/local/lib/python2.7/dist-packages/nolearn/lasagne/base.py", line 359, in initialize
    self.y_tensor_type,
  File "/usr/local/lib/python2.7/dist-packages/nolearn/lasagne/base.py", line 496, in _create_iter_funcs
    allow_input_downcast=True,
  File "/home/gunslinger/src/theano/theano/compile/function.py", line 297, in function
    "In() instances and tuple inputs trigger the old "
NotImplementedError: In() instances and tuple inputs trigger the old semantics, which disallow using updates and givens

**Comment by dnouri** [comment]
Trying to reproduce this.  Which versions (git commits) of Theano and nolearn are you using?

**Comment by dnouri** [comment]
Closing because of lack of feedback.  If anyone sees this issue, please reopen.

**Comment by NeoPolus** [comment]
Happened to me too when calling `NeuralNet.fit`:
```
NotImplementedError                       Traceback (most recent call last)
/usr/lib/python2.7/dist-packages/IPython/utils/py3compat.pyc in execfile(fname, *where)
    202             else:
    203                 filename = fname
--> 204             __builtin__.execfile(filename, *where)

/home/blopsoi/tmp/pruebann2.py in <module>()
    127     verbose=1,
    128     )
--> 129 nn.fit(trainX, trainY)
    130 
    131 

/usr/local/lib/python2.7/dist-packages/nolearn-0.6adev-py2.7.egg/nolearn/lasagne/base.pyc in fit(self, X, y, epochs)
    525             y = self.enc_.fit_transform(y).astype(np.int32)
    526             self.classes_ = self.enc_.classes_
--> 527         self.initialize()
    528 
    529         try:

/usr/local/lib/python2.7/dist-packages/nolearn-0.6adev-py2.7.egg/nolearn/lasagne/base.pyc in initialize(self)
    365         iter_funcs = self._create_iter_funcs(
    366             self.layers_, self.objective, self.update,
--> 367             self.y_tensor_type,
    368             )
    369         self.train_iter_, self.eval_iter_, self.predict_iter_ = iter_funcs

/usr/local/lib/python2.7/dist-packages/nolearn-0.6adev-py2.7.egg/nolearn/lasagne/base.pyc in _create_iter_funcs(self, layers, objective, update, output_type)
    502             outputs=[loss_train],
    503             updates=updates,
--> 504             allow_input_downcast=True,
    505             )
    506         eval_iter = theano.function(

/usr/local/lib/python2.7/dist-packages/theano/compile/function.pyc in function(inputs, outputs, mode, updates, givens, no_default_updates, accept_inplace, name, rebuild_strict, allow_input_downcast, profile, on_unused_input)
    246         if uses_updates or uses_givens:
    247             raise NotImplementedError(
--> 248                     "In() instances and tuple inputs trigger the old "
    249                     "semantics, which disallow using updates and givens")
    250         fn = orig_function(inputs, outputs,

NotImplementedError: In() instances and tuple inputs trigger the old semantics, which disallow using updates and givens
```

```
$ pip show nolearn
---
Name: nolearn
Version: 0.6adev
Location: /usr/local/lib/python2.7/dist-packages/nolearn-0.6adev-py2.7.egg
Requires: gdbn, joblib, scikit-learn, tabulate, Lasagne
$ sudo pip show theano 
---
Name: Theano
Version: 0.8.2
Location: /usr/local/lib/python2.7/dist-packages
Requires: numpy, scipy, six
$ sudo pip show scipy             
---
Name: scipy
Version: 0.13.3
Location: /usr/lib/python2.7/dist-packages
Requires: 
```


I solved it by doing (some of the steps might not be necessary, but worked anyhow):

```
$ sudo apt-get install python-numpy python-scipy python-matplotlib ipython ipython-notebook python-pandas python-sympy python-nose
$ sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran
$ sudo pip install --upgrade scipy   # This takes a while!
$ sudo pip install --upgrade theano    # This takes a while!
```
