### ISSUE TITLE
access weights of neural network. 

### ISSUE THREAD

**Issue by great-thoughts** [dnouri/nolearn#213]
After training a neural network, in what variable is the weights of the neural network saved?

I want to find what are the values of my weights.

**Comment by BenjaminBossan** [comment]
Usually, the Theano shared values are stored in the Lasagne layers' `W` (weights) and `b` (biases) attributes. To get numpy arrays, you would do something like this:

```
weights = net.layers_['dense'].W.get_value()
```

(insert appropriate names)

For more details, you should consult the Lasagne docs.

**Comment by dnouri** [comment]
There's also `net.get_all_params_values()`, which returns a dict with `{layer_name: list_of_numpy_arrays}` containing all your network's parameters.
