### ISSUE TITLE
Cannot modify max_epochs and rerun fit()

### ISSUE THREAD

**Issue by ferrouswheel** [dnouri/nolearn#214]
It'd be nice to be able to run `network.fit(X, Y)` with a network until `network.max_epochs` is reached, then change `max_epochs` to a higher number and call fit again to have training continue.

This would be possible if the [condition in `train_loop`](https://github.com/dnouri/nolearn/blob/master/nolearn/lasagne/base.py#L563) used `num_epochs_past` as the initial value for epoch rather than 0:

```python
num_epochs_past = len(self.train_history_)
epoch = num_epochs_past # epoch was previously assigned to 0

while epoch < epochs:
    ...
```

Of course, it was probably intended that calling `max_epochs` applies independently for each call to `fit()` and if that's the case it'd be good for future documentation to mention this. In the mean time, they'll be this github issue that people can find by google ;-)

**Comment by BenjaminBossan** [comment]
Yes, this behavior may be a little bit unintuitive for some but I don't think it needs to be changed.

Btw., you can pass the number of epochs you want to train directly to the fit call instead of setting `max_epochs`.
