### ISSUE TITLE
Suggestion: add a parameter to stop fitting after n epochs without improvement

### ISSUE THREAD

**Issue by vabatista** [dnouri/nolearn#217]
I'd like to suggest to add a parameter to NeuralNet to stop fitting after n epochs without improvement in validation score.

The ideia is same behind early_stopping_rounds  in xgboost: http://xgboost.readthedocs.org/en/latest/python/python_api.html

**Comment by dnouri** [comment]
Are you aware of the event handlers?  You can use 'on_epoch_finished' to
easily implement what you're describing.  There's also a 'EarlyStopping'
implementation in the facial keypoints tutorial.

**Comment by vabatista** [comment]
Thanks. I'll look for this solution.
