### ISSUE TITLE
Problem with neural nets weights

### ISSUE THREAD

**Issue by jielu0728** [dnouri/nolearn#219]
Hi,

I'd like to know that after finishing fitting a model in lasagne, and saving the model with pickle, is the model with the lowest validation error saved or the model of the last epoch saved or all models in the history?

Because I saw your function earlystopping stocks the weights of best model until the last epoch. As using the model with the lowest validation error to predict may help us get better results, and in many cases as I see that model isn't the last one.

Best regards,
Jie

**Comment by dnouri** [comment]
To set back the weights to those that achieved the lowest validation error after training is finished, use the [RememberBestWeights](https://github.com/dnouri/nolearn/blob/7e23fadd8a01d37ba8442e904025435c2c0e54cc/nolearn/lasagne/handlers.py#L116) handler like this:

```python
from nolearn.lasagne import RememberBestWeights

    rbw = RememberBestWeights()
    net = NeuralNet(
        # ...
        on_epoch_finished=[rbw],
        on_training_finished=[rbw.restore],
        )
```
