### ISSUE TITLE
cannot import Objective

### ISSUE THREAD

**Issue by skawnain04** [dnouri/nolearn#220]
I am getting an import error while trying to run my code. it says lasagne.objectives import Objective ImportError: cannot import name Objective. can anyone please help me to solve this problem

**Comment by dnouri** [comment]
`Objective` was one of the things we had to remove without backward compatibility.  [This](https://github.com/dnouri/nolearn/blob/7e23fadd8a01d37ba8442e904025435c2c0e54cc/nolearn/lasagne/base.py#L153) is how the new objective interface looks like.  You should be able to use it in a similar way.  Let me know if you need more help.
