### ISSUE TITLE
NoLearn 0.7 requires scipy 0.16,  but Theano 0.8 & Lasagne 0.2 require scipy 0.17

### ISSUE THREAD

**Issue by hobson** [dnouri/nolearn#222]
Building wheels or conda packages based on this master branch (0.7 version) results in a downgrade of scipy and that may break Theano or Lasagne.

**Comment by dnouri** [comment]
We should update the requirements list to newer version.  I'm curious though, where do Theano and Lasagne say they require scipy 0.17?

**Comment by unautre** [comment]
The only place I can find saying that Theano requires Scipy is [here](https://github.com/Theano/Theano/blob/master/doc/install.txt#L35), and it only needs scipy >= 0.11. Lasagne only seems to require scipy through Theano.

**Comment by hobson** [comment]
Interesting. And Theano try/excepts the scipy import, accepting versions all the way back to 0.7:

```python
try:
	    import scipy
	    scipy_ver = [int(n) for n in scipy.__version__.split('.')[:2]]
	    enable_sparse = bool(scipy_ver >= [0, 7])
```

But when you pip install Theano it installs the most recent scipy. And theano works well with the most recent scipy sparse matrices. So installing the most recent scipy with a `>=` probably makes sense for nolearn too. Since theano isn't maintaining/testing a version that hard-depends, with `==`, on an older scipy version.

**Comment by dnouri** [comment]
@hobson The use of `requirements.txt` is pretty much optional.  You can pip install nolearn (e.g. `pip install .` within a Git checkout) and it won't require any specific version of scipy since the list of dependencies in setup.py isn't pinned.

**Comment by hobson** [comment]
Yea, thank you. I have no problem on my environment. I just ran into this
trying to build conda packages for code school students on Windows. Not an
issue for you or most of your users, I'm sure. Theano never worked well on
Windows for them anyway (g++ compiler, etc).

--Hobson
(503) 974-6274
gh <https://github.com/hobson/> twtr <https://twitter.com/hobsonlane> li
<https://www.linkedin.com/in/hobsonlane> g+
<http://plus.google.com/+HobsonLane/> so
<http://stackoverflow.com/users/623735/hobs>

**Comment by dnouri** [comment]
OK I'll close this issue since doing `pip install Theano` and `pip install git+https://github.com/dnouri/nolearn.git@master#egg=nolearn==0.7.git` will just work.  Let me know if I misunderstood, or if there's anything else we can do in nolearn to support your use case better.

**Comment by hobson** [comment]
You're right. Your pip install order upgraded scikitlearn from 17.0 for
Theano to 17.1 for nolearn. Thanks.

--Hobson
(503) 974-6274
gh <https://github.com/hobson/> twtr <https://twitter.com/hobsonlane> li
<https://www.linkedin.com/in/hobsonlane> g+
<http://plus.google.com/+HobsonLane/> so
<http://stackoverflow.com/users/623735/hobs>
