### ISSUE TITLE
TypeError: __init__() got multiple values for keyword argument 'scales'

### ISSUE THREAD

**Issue by CAWilson94** [dnouri/nolearn#232]
Trying to change the scales parameter when calling the dbn class in nolearn 0.5:

```
dbn = DBN(
	# [[numNodes input layer], numNodes hidden layer, numNodes output layer ]
	hiddenAr,
	# Learning rate of algorithm
	learn_rates,
	learn_rates_pretrain = 0.01,
	# Decay of learn rate
	learn_rate_decays=1,
	# Iterations of training data (epochs)
	epochs=ep,
	# Verbosity level
	verbose=1,
	momentum=mom,
	scales = 0.03,
	use_re_lu = True
	)  
```

Getting the error described in the title. Not sure why.

**Comment by dnouri** [comment]
You're passing the arguments wrongly.  Try passing them all as keyword arguments.  You'll notice that the second argument is `scales`, so effectively you're passing `scales` once as the second positional argument here `learn_rates`, and once as keyword argument `scales=0.03`.
