### ISSUE TITLE
Install of requirements failed

### ISSUE THREAD

**Issue by aflyax** [dnouri/nolearn#234]
Running this command:

`pip install -r https://raw.githubusercontent.com/dnouri/nolearn/master/requirements.txt`

results in:

`Failed building wheel for scipy`
…
`Command "/home/aflyax/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-yekvv38i/scipy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-xdhx23wz-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-yekvv38i/scipy/`

**Comment by unautre** [comment]
Looks like you are using Anaconda. You should probably install using Anaconda own's package manager,
`conda install scipy`

**Comment by dnouri** [comment]
After what @unautre suggested, download the requirements.txt file and remove the lines with requirements that you have already satisfied via conda (maybe numpy, scipy).  Then run `pip install -r requirements.txt` with your local, modified requirements.txt file.

Please reopen if this does not fix your issue.
