### ISSUE TITLE
Loading weights - what is stored and fetched ?

### ISSUE THREAD

**Issue by run2** [dnouri/nolearn#24]
Daniel
When I pickle a network and later load it's weights - do/should I need to make sure that I am loading weights into a network which has the same number of neurons ? I would normally assume so. But I am seeing that I am able to load weights from a network into another where there is substantial difference in the number of filters, number layers etc.
So, what is going on underneath ? Specially with such storing and loading between networks which have conv layers, pool layers and hidden layers.

Thanks
Regards

**Comment by dnouri** [comment]
The implementation of `NeuralNet` will try to copy weights from filters that match up; they should be in the same position, and have the same number of parameters.  That's what the implementation does here: https://github.com/dnouri/nolearn/blob/master/nolearn/lasagne.py#L349

**Comment by run2** [comment]
Hmm - thanks. I had a network with 32,64,128 kernels in 3 convpool layers (followed by 3 dense layers). I loaded it into another network with 64,138,256 kernels (rest remaining the same). So ideally that should have been as good as a fresh start  ? or only the dense layers will have a trained start while the rest have a fresh start ?

**Comment by dnouri** [comment]
Yes, your dense layers will be initialized with those weights.  I think @benjaminbossan has code that adds a little bit of feedback to `load_weights_from`, so that as a user, you'll know which weights were copied and which weren't.

**Comment by run2** [comment]
Thanks

**Comment by BenjaminBossan** [comment]
I have the code here:
https://github.com/BenjaminBossan/nolearn
Just take that code or copy from the lasagne.py module. There are no tests yet, I hope it works. It did for me.

I would have made a pull request but I don't exactly know how to yet and am short on time. Good luck.

**Comment by run2** [comment]
Thanks Benjamin
