### ISSUE TITLE
DeCAF ImageNet link broken in the documentation

### ISSUE THREAD

**Issue by mluszczyk** [dnouri/nolearn#245]
In this file:

https://github.com/dnouri/nolearn/blob/master/docs/decaf.rst

the following URL is referred:

http://www.eecs.berkeley.edu/~jiayq/decaf_pretrained/

It redirects to 404 page. How can I download those data?

**Comment by dnouri** [comment]
Best to [contact the author](http://daggerfs.com/).  The link from his own website is broken too.
