### ISSUE TITLE
plot_conv_weights breaks with 1 filter

### ISSUE THREAD

**Issue by markveillette** [dnouri/nolearn#246]
I'm having trouble visualizing a Conv2DLayer when I set num_filters=1.  

I'm running 
theano='0.8.0.dev-RELEASE'
lasagne=0.2.dev1

Here's a stripped down example:

```python
    %matplotlib inline
    import numpy as np
    from lasagne.layers import InputLayer,Conv2DLayer,FlattenLayer
    from nolearn.lasagne import NeuralNet
    from nolearn.lasagne.visualize import plot_conv_weights

    def make_simple_network( num_filters ):
      # Set up a NN with a conv2 layer
      net = NeuralNet(
          layers = [  
            (InputLayer,{
                'name' :'input_X',
                'shape':(None,1,4,4) }),
            (Conv2DLayer,{
                'name'       :'conv2_layer',
                'num_filters': num_filters, 
                'filter_size': (4,4) 
            } ),
           (FlattenLayer,{
                'name':'out_flat'
            })
         ],
        update_learning_rate=0.9
      )
      net.initialize()
      return net

    # This works fine
    net = make_simple_network( num_filters=4 )
    plot_conv_weights( net.layers_['conv2_layer'] )

    # Breaks with num_filters=1
    net = make_simple_network( num_filters=1 )
    plot_conv_weights( net.layers_['conv2_layer'] )
```

Here's the error message:

    AttributeError                            Traceback (most recent call last)
    <ipython-input-28-91cf37dda446> in <module>()
          1 # Breaks with 1 filter
          2 net = make_simple_network( num_filters=1 )
    ----> 3 plot_conv_weights( net.layers_['conv2_layer'] )

    G:\Programs\Anaconda2\lib\site-packages\nolearn-0.6a0.dev0-py2.7.egg\nolearn\lasagne\visualize.pyc in plot_conv_weights(layer, figsize)
         39         figs, axes = plt.subplots(nrows, ncols, figsize=figsize)
         40 
    ---> 41         for ax in axes.flatten():
         42             ax.set_xticks([])
         43             ax.set_yticks([])

    AttributeError: 'AxesSubplot' object has no attribute 'flatten'

**Comment by BenjaminBossan** [comment]
Hmm, that's a pretty clever way of breaking the code ;)

No, seriously, I never thought of that special case. If you need a quick solution, comment out these lines of code (41-44).

**Comment by markveillette** [comment]
Yeah, this is definitely an edge case but I though I would let you know :)

Upon closer inspection it looks like `plt.subplots` doesn't return a numpy.array if nrows=ncols=1, but it does if either is larger than 1.  Here was my quick fix:

    38     for feature_map in range(shape[1]):
    39         figs, axes = plt.subplots(nrows, ncols, figsize=figsize)
    40         if type(axes)!=np.ndarray : # Happens if nrows=ncols=1
    41             axes = np.array([[axes]])
    42

**Comment by dnouri** [comment]
@BenjaminBossan What are our chances for a PR?  :-)

**Comment by BenjaminBossan** [comment]
@markveillette could you please test if the error still occurs with the current version of nolearn? If not, this issue should be solved.

**Comment by markveillette** [comment]
Works great now,  thanks!
