### ISSUE TITLE
Sklearn GridSearchCV compatible assigning weights for unbalanced classes 

### ISSUE THREAD

**Issue by ChinookPDX** [dnouri/nolearn#258]
Hi,

I'm looking for a way to use class weights with nolearn to compensate for unbalanced classes. I'll be using this with GridSearchCV. Is this possible? If it is, is there an example I can start from?

Thanks.

**Comment by acganesh** [comment]
One way to handle class imbalance is to implement resampling on top of nolearn's `BatchIterator`. Here's an example, adapted from Mathis Antony's code [here](https://github.com/sveitser/kaggle_diabetic/blob/master/iterator.py#L113).

```python
import numpy as np
from nolearn.lasagne import BatchIterator, NeuralNet


def balance_per_class_indices(y, weights):
    """
    Returns indices to resample classes according to weights.

    y: NumPy array containing class labels.
    weights: NumPy array containing weights for each class.
    """

    # p will represent the probability distribution used to sample
    # each element in y.
    p = np.zeros(len(y))
    for i, weight in enumerate(weights):
        p[y == i] = weight
    return np.random.choice(np.arange(len(y)), size=len(y),
                            replace=True, p=np.array(p) / p.sum())


class ResampleIterator(BatchIterator):
    """Iterator that incorporates class resampling."""
    def __init__(self, weights, *args, **kwargs):
        self.weights = weights
        super(ResampleIterator, self).__init__(*args, **kwargs)

    def __call__(self, X, y=None):
        if y is not None:
            indices = balance_per_class_indices(y, weights=self.weights)
            X = X[indices]
            y = y[indices]
        return super(ResampleIterator, self).__call__(X, y)
```

Then, for example, you can create a `NeuralNet` object:

```python
weights = np.array([1.0, 2.0, 3.0, 4.0])
net = NeuralNet(
    # ...
    batch_iterator_train=ResampleIterator(batch_size=100,
                                          weights=weights),
    # ...
    )
```


You can also customize this if you'd like -- for example, you can recalculate `weights` at each call of `ResampleIterator` if you want to resample on a variable schedule.  

Hope this is helpful.

**Comment by ChinookPDX** [comment]
Thank you very much for posting the code. I'm away from my workstation this week.. I'll try your suggestions and get back next week.

Thanks.

**Comment by acganesh** [comment]
Great -- very happy to help.
