### ISSUE TITLE
Is there an option in NeuralNet to change the training data at each epoch ?

### ISSUE THREAD

**Issue by ibrahmd** [dnouri/nolearn#259]
I would like to add some random noise to my training data and train on that at the beginning of each epoch.

I tried modifying train_test_split but I realized that it only gets called once at the beginning.

Is there a way to force NeuralNet to call train_test_split after each epoch ? or any other way to make that work ?

Thanks

**Comment by BenjaminBossan** [comment]
The easiest way to provoke several calls fit calls, e.g. by calling the `partial_fit` method.

From your description, however, I don't think this is what you want. If you make different train/test splits, this will result in your validation score becoming unreliable.

Instead, you should have a look at the [BatchIterator](https://github.com/dnouri/nolearn/blob/master/nolearn/lasagne/base.py#L69). You should subclass it and override the `transform` method to add random noise to your data.

**Comment by ibrahmd** [comment]
OK, to make the problem clear again. I have for instance 100K trainining data called X. Each epoch I want to:
- Create X_transormed = X + random noise
- Train network on X_transformed


I looked at BatchIterator but I am not sure how to use it after overriding `BatchIterator`. How can I tell NeuralNet to get data from `transform` at each iteration? Is there an example code of how it can be used ?

Thanks

**Comment by BenjaminBossan** [comment]
The `BatchIterator` splits your whole data into smaller batches, which in turn are piped through the `transform` method. What you could do is something similar to this:

```
import numpy as np
from nolearn.lasagne import BatchIterator
from nolearn.lasagne import NeuralNet

class NoisyBatchIterator(BatchIterator):
    def transform(self, Xb, yb):
        # uniform distribution, maybe you rather need normal --> np.random.randn?
        noise = np.random.random(Xb.shape)
        # you should probably scale your noise
        noise = 0.1 * (noise - 0.5)
        return Xb + noise, yb

...

net = NeuralNet(..., batch_iterator_train=NoisyBatchIterator())
```

I have not tested this code but this is how I understand your problem.

Alternatively, there is a layer in [Lasagne](https://github.com/Lasagne/Lasagne/blob/master/lasagne/layers/noise.py#L92) that adds noise. However, it would also add noise during predictions, which is probably not what you want to do.

**Comment by dnouri** [comment]
> Alternatively, there is a layer in Lasagne that adds noise. However, it would also add noise during predictions, which is probably not what you want to do.

`GaussianNoiseLayer` does not add noise when `deterministic=True`, i.e. during predictions.
