### ISSUE TITLE
Remove explicit `objective_loss_function` from `NeuralNet`

### ISSUE THREAD

**Issue by cancan101** [dnouri/nolearn#263]
This will allow for `objective` that do not take a `loss_function`.

**Comment by dnouri** [comment]
What does "explicit" mean?  What are you suggesting?

I have a hunch ;-) that for what you're trying to do, it suffices to pass a custom `loss_function` instead of overriding the `objective` itself?

**Comment by dnouri** [comment]
Closing due to lack of response.
