### ISSUE TITLE
Randomizing Batches in training gives bad predictions though validation errors are much less

### ISSUE THREAD

**Issue by run2** [dnouri/nolearn#27]
Hi
I posted this on nolearn too, but may be dnouri is away for a while. Any help will be really appreciated as I really need to understand this asap. Please feel free to close this.

The BatchIterator uses a loop as below
for i in range((n_samples + bs - 1) / bs):

That means - for each epoch, the training progresses through the set of batches in the same sequence.
I wanted to see what happens if I randomize the sequence of batches.
So I added this code

    v = [i for i in range((n_samples + bs - 1) / bs)]
    random.shuffle(v)
    for i in v:
    #for i in range((n_samples + bs - 1) / bs):
This means, each epoch will have the sequence of batches different. It will go through all the images - but in a different sequence.

This change gave me much faster descent and considerably lower validation errors. So I was happy. 
BUT - the prediction on the (same) test set plummeted like hell. From 86% to 33%.

Why ?

Similarly, I trained with the unmodified loop and stored a net. I loaded that net in a separate code, and used it to predict on a test set. Once with the unmodified loop, once with the modified loop. Again the same behavior, massive decrease in the unmodified loop BatchIterator.

For the fact of the matter, I never thought that the decrease can be caused by the BatchIterator during prediction. It was after several hours of playing around that I figured.

So again question - what is happening here ? Why the prediction on same test set is so bad when using my modified loop even though the validation errors are much lower during training ? And what is the BatchIterator being used for while prediction ?

Thanks a lot helping out in advance

**Comment by dnouri** [comment]
What's happening here is that you're probably also shuffling the batches of your test set iterator (`batch_iterator_test`).  When you run net.predict() it'll also use an iterator to go over the samples, so in your case they'll come out in this random order.

**Comment by run2** [comment]
Daniel
I am unaware of batch_iterator_test. Like I said I only changed those three lines in BatchIterator. And I am not sure I understand what you mean. Why would that cause extremely bad test performance when the validation errors are less. Why would the prediction have dependency on the order of the batches ?

**Comment by dnouri** [comment]
@run2 So if you're running the version that doesn't have `batch_iterator_test` (which was added [three weeks ago](https://github.com/dnouri/nolearn/commit/ad0b167672af14397ac82401ffd259c88e4f0760)), then put a `if self.test` around your shuffling logic, so it won't shuffle if it's in test mode.

Why would the prediction depend on the order of the batches?  Because that order defines the order of predictions on the way out.  So imagine you want to predict for values A, B, and C.  After your batch iterator's shuffle (assume batch size of 1), the predictions might come out as b, c, and a.  If this doesn't make sense, then I suggest you take a closer look at the [predict_proba method](https://github.com/dnouri/nolearn/blob/master/nolearn/lasagne.py#L239-L243).

**Comment by run2** [comment]
Ah! I see. Very interesting. Thanks - let me try that out.

**Comment by run2** [comment]
Wow! That makes a big difference now. Much much better prediction results. You might want to try out what I did and see if that gives you much faster learning and lower val errors. It will be great if you can let me know.

**Comment by run2** [comment]
I am closing this issue but waiting to hear from you.

**Comment by dnouri** [comment]
I think this is a fine idea.  FTR, here's some code that I use in another project:
```python
def shuffle(*arrays):
    p = np.random.permutation(len(arrays[0]))
    return [array[p] for array in arrays]

# ...

class ShufflingBatchIteratorMixin(object):
    def __iter__(self):
        self.X, self.y = shuffle(self.X, self.y)
        for res in super(ShufflingBatchIteratorMixin, self).__iter__():
            yield res
```

**Comment by cancan101** [comment]
@dnouri For the reasons listed here: #36, there are limitations to this approach.

**Comment by dnouri** [comment]
@cancan101 Not sure I get it. Is `nn.enc_` relevant for shuffling?

**Comment by cancan101** [comment]
I am using is not for shuffling but for subsampling one of the classes.

**Comment by dnouri** [comment]
So you suggest #36 as an alternative to the code in #13, is that right?

**Comment by cancan101** [comment]
Ah, yes. In looking at [your code above](https://github.com/dnouri/nolearn/issues/27#issuecomment-71175381), I think that is a much cleaner solution and doesn't require the change in #13 and subclassing of `NeuralNet`. I would be happy to use change/ subclass the Iterator but currently I do need a reference to the `NeuralNet`.
