### ISSUE TITLE
Train class probabilities instead of hard labels

### ISSUE THREAD

**Issue by EliasVansteenkiste** [dnouri/nolearn#274]
Is it possible to learn class probabilities instead of hard labels?
E.g. [0.1, 0.15, 0.25, 0.5] instead of  class 3 ~ [0, 0, 0, 1]
Similar to predict and predict_proba functions, it would be useful to have a fit_proba method.

I simply (naively) tried to feed the class probabilities to the partial_fit method, but it fails with the following error:
```
    netSpec.partial_fit(fragment_xVal,new_fragment_probabilities)
  File "/usr/local/lib/python2.7/dist-packages/nolearn/lasagne/base.py", line 527, in partial_fit
    return self.fit(X, y, epochs=1)
  File "/usr/local/lib/python2.7/dist-packages/nolearn/lasagne/base.py", line 521, in fit
    self.train_loop(X, y, epochs=epochs)
  File "/usr/local/lib/python2.7/dist-packages/nolearn/lasagne/base.py", line 531, in train_loop
    X_train, X_valid, y_train, y_valid = self.train_split(X, y, self)
  File "/usr/local/lib/python2.7/dist-packages/nolearn/lasagne/base.py", line 133, in __call__
    kf = StratifiedKFold(y, round(1. / self.eval_size))
  File "/opt/python_pkgs/scikit-learn/sklearn/cross_validation.py", line 544, in __init__
    label_test_folds = test_folds[y == label]
IndexError: too many indices for array
```
I digged in the code of nolearn, but it doesn't seem that straightforward to change it to accept probabilities instead of class labels.
Or is there an easier way to do this?

Thanks in advance

**Comment by BenjaminBossan** [comment]
You should be able to achieve this by using a regression with four output dimensions. The nonlinearity should be softmax if you want your probabilities to add up to 1. Depending on your goal, you might have to adjust the objective as well. I rarely find it useful to predict such "soft targets", but you should know best.

**Comment by EliasVansteenkiste** [comment]
Thanks, this works great.
Soft targets are interesting for transferring 'dark knowledge' from a larger network to a smaller one.

Hinton, G. E., Oriol Vinyals, and Jeff Dean. "Dark knowledge." Presented as the keynote in BayLearn (2014).
