### ISSUE TITLE
Convolutional Autoencoder NaN

### ISSUE THREAD

**Issue by sampepose** [dnouri/nolearn#275]
Hi! I'm trying to make a convolutional autoencoder based off of VGG-S (https://github.com/Lasagne/Recipes/blob/master/modelzoo/vgg_cnn_s.py).

For some reason, learning always converges to NaN almost immediately. I think my architecture is correct from VGG-S, so I'm not sure why this is happening.

<img width="504" alt="screenshot 2016-06-09 10 07 57" src="https://cloud.githubusercontent.com/assets/1855931/15938905/23c4c5a8-2e2a-11e6-948a-926c32976131.png">

Here's my code (https://gist.github.com/sampepose/ccb58557271cff10d182f4ab8282f3b4).

**Comment by BenjaminBossan** [comment]
Hi. You should definitely have another nonlinearity in the last layer. My suggestion is to use sigmoid and to normalize the target to [0, 1]. If that doesn't help, I would play with different learning rates.

**Comment by dnouri** [comment]
I'd be curious to see what the architecture looks like.  And if Op ever figured out what was wrong with his example.  @BenjaminBossan's advices likely to help

Theano has documentation on [Dealing with NaNs](http://deeplearning.net/software/theano/tutorial/nan_tutorial.html) which should also help.
