### ISSUE TITLE
Best way to reuse layers from another model for a new model

### ISSUE THREAD

**Issue by lzuwei** [dnouri/nolearn#277]
Hi all,

I have a model say an autoencoder with 8 layers:
input layer 1200
layer 1: 2000
layer 2: 1000
layer 3: 500
layer 4: 50
layer 5: 500
layer 6: 1000
layer 7: 2000
layer 8: 1200

If I want to create a new model with say 5 layers with the first 4 layers reused from the autoencoder and last layer with something else eg: DenseLayer with softmax. What is the recommended way to reuse the layers.

Many thanks for any tips!

**Comment by BenjaminBossan** [comment]
The `load_params_from` method will match the layers by name and their parameter's shape. If you make a second net with your desired architecture and match the names of the layers that are supposed to be copied, this should work:

```
new_net.load_params_from(old_net)
```

When verbosity is set to > 0, the net will even tell you which parameters were matched.

**Comment by dnouri** [comment]
Assuming this question was sufficiently answered.
