### ISSUE TITLE
Request for Python 3 support

### ISSUE THREAD

**Issue by jseabold** [dnouri/nolearn#28]
Would be nice. Right now I'm hacking together a solution with `use_2to3` and fixing things as they come up for me. Nothing systematic.

See also my comment here https://github.com/benanne/Lasagne/issues/23

**Comment by dnouri** [comment]
Implemented in a4c318a8fa613311b5a1383aa241baafa755c974 (in master).  Let me know how it works for you.

**Comment by jseabold** [comment]
Awesome, thanks, I will check it out and report back.
