### ISSUE TITLE
Prediction using learned weights

### ISSUE THREAD

**Issue by alexvpickering** [dnouri/nolearn#281]
I'm trying to transfer a neural network to an R package I wrote, but I can't figure out how to reproduce the `predict` function using the learned weights. The `net1` layout is this:

n    | name        | size
-----|-------------- | ------
  0  | input         |  23050 
  1  | dropout1   |  23050 (p=0.85)
  2  | hidden       |  2500 (nonlinearity=very_leaky_rectify)
  3  | dropout2   |   2500 (p=0.5)
  4  | output       |  11525 (nonlinearity=None)

Here is what I tried:

```
W1 = net1.get_all_params_values()['hidden'][0]
W2 = net1.get_all_params_values()['output'][0]

# X is matrix I would like to get predictions for 
z2 = np.dot(X, W1) 
a2 = np.maximum(1./3*z2, z2)
z3 = np.dot(a2, W2) 
yhat = z3
```
This gives me a result close to `net1.predict(X)` though slightly off. What am I missing? I suspect it has something to do with the vectors `net1.get_all_params_values()['hidden'][1]` and `net1.get_all_params_values()['output'][1]`?

 Thank you for the AWESOME package!

**Comment by alexvpickering** [comment]
I think I figured it out. I needed to add `net1.get_all_params_values()['hidden'][1]` to z2 and `net1.get_all_params_values()['output'][1]` to z3. Still not exactly sure what they are though.

**Comment by BenjaminBossan** [comment]
Hi Alex, I'm glad you figured it out on your own. Those additional parameters are the "biases", search for "neural network weights biases" and you will find plenty of explanations.
