### ISSUE TITLE
Citing nolearn

### ISSUE THREAD

**Issue by kungfujam** [dnouri/nolearn#285]
I made use of nolearn in my thesis and would like to cite it. Do you have a preference for how you would like to be cited?

**Comment by BenjaminBossan** [comment]
That is a question @dnouri should answer. There seems to be a [process for this](https://guides.github.com/activities/citable-code/), which for instance makes sure the cited code is frozen.

**Comment by dnouri** [comment]
@kungfujam If not too late you can [use this](https://github.com/dnouri/nolearn#citation)

**Comment by kungfujam** [comment]
You missed me by a week! For your reference, I cited you as:
@misc{nolearn,
author = {Nouri, Daniel},
title = {{``nolearn: Abstractions around neural net libraries, most notably Lasagne.'' [Online]. Available: https://github.com/dnouri/nolearn [Accessed 07/Aug/2016]}},
year = {2016}
}

I'm very sorry. I will update to your citation in future publications i.e.
@misc{nolearn,
author = {Nouri, Daniel},
title = {{nolearn: scikit-learn compatible neural network library https://github.com/dnouri/nolearn}},
year = {2014}
}
