### ISSUE TITLE
scores_train/valid take different parameters than custom_scores

### ISSUE THREAD

**Issue by DanChianucci** [dnouri/nolearn#287]
custom_scores are defined as 

`function(target, prediction)`

while scores_train and scores_valid are defined as 

`function(predict, target)`

I'm not sure if this was intentional, but it makes it somewhat confusing

**Comment by dnouri** [comment]
I agree it's confusing and it's mostly an accident.  `custom_scores` was first introduced and uses the scikit-learn metrics interface ([an example here](http://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html)), while `scores_train` and `scores_valid` use Lasagne's [objectives](https://github.com/Lasagne/Lasagne/blob/master/lasagne/objectives.py) interface where the arguments are `predictions, target`, so the other way around.
