### ISSUE TITLE
Pull requests

### ISSUE THREAD

**Issue by run2** [dnouri/nolearn#29]
Hi Daniel
Can you let me know the general rule, process and contract for making contribution to Nolearn.

Regards

**Comment by dnouri** [comment]
Pull requests are welcome. If you have something you'd like to improve, having code ready that implements the change helps a lot, and it's more likely it'll be done sooner (once there's consensus that the general idea is good -- you might wanna ask if unsure).  You'll probably want to add a test for a new feature.

**Comment by run2** [comment]
Daniel
I have already done and am using a code to load weights by layer type. 
I wanted to add that if it is helpful to others.

**Comment by dnouri** [comment]
I've added a little comment to the tutorial where you've mentioned the same thing; I think the recent addition of a 'name' for Lasagne layers is good news for us, and it means that layer weights can be copied maybe more reliably than by type.  Check my comments there.  I think it'll be useful to see your code anyway, also to see how you've implemented the AE, something that others might want to try as well.

**Comment by run2** [comment]
Here it is https://gist.github.com/run2/e7162610e759a3453156. It is nothing fancy. I can improve it further if it is helpful to others

**Comment by dnouri** [comment]
Thanks for sharing this.  I think it'll ultimately be more useful to match layers by name here.  Lasagne just recently added names to layers.  We should use these, and then copying weights becomes just a matter of matching names.
