### ISSUE TITLE
Multiple Input layers?

### ISSUE THREAD

**Issue by EliasVansteenkiste** [dnouri/nolearn#292]
I want to feed the metadata of an image to my network.

How should I get started with implementing a network with two input layers?
Is it possible with nolearn? 

Let's say I have an input image with the following shape 3x32x32 and a 10 metadata features.
I define two input layers:
```
li1= InputLayer(shape=(None, 3, 32, 32))
li2= InputLayer(shape=(None, 10))
```
What shape should my input data have that is fed to the fit function?
`netSpec.fit(xTrain, yTrain)`
What should the shape of xTrain be?

**Comment by dnouri** [comment]
You'll have to name your input layers, e.g.

`li1= InputLayer(shape=(None, 3, 32, 32), name='input1')`

and then pass ``X`` as a dictionary:

`netSpec.fit({'input1': X1, 'input2': X2}, yTrain)`
