### ISSUE TITLE
AttributeError: 'NeuralNet' object has no attribute 'scores_train'

### ISSUE THREAD

**Issue by Pengwei-Yang** [dnouri/nolearn#294]
Trained and pickle saved NeuralNet model with nolearn==0.6a0.dev0; Theano==0.7.0; Lasagne==0.2.dev1. Right now try to load and use the model to test new dataset with current version of nolearn==0.6.0; Theano==0.8.0; -e git+https://github.com/Lasagne/Lasagne.git@8f4f9b26b90abcb303da2cbe9ab04f63676aa6bf#egg=Lasagne, attributeError showed up as the following: 

File "/usr/lib/python2.7/site-packages/nolearn/lasagne/base.py", line 804, in __setstate__
    self.initialize()
  File "/usr/lib/python2.7/site-packages/nolearn/lasagne/base.py", line 372, in initialize
    self.y_tensor_type,
  File "/usr/lib/python2.7/site-packages/nolearn/lasagne/base.py", line 494, in _create_iter_funcs
    s[1](predict_proba, y_batch) for s in self.scores_train]
AttributeError: 'NeuralNet' object has no attribute 'scores_train'

Anyway to fix it and still able to use the saved model? Thanks very much!

**Comment by dnouri** [comment]
Yes go to that line 494 in base.py and change it to read `s for s in getattr(self, 'scores_train', [])]`. Note the use of getattr and the fallback to empty list of that attribute isn't present.

**Comment by Pengwei-Yang** [comment]
Hi Daniel:

Your suggestion has fixed the problem. Thank you so much!

Best,

Pengwei
