### ISSUE TITLE
2 networks with shared layers

### ISSUE THREAD

**Issue by EliasVansteenkiste** [dnouri/nolearn#300]
We have a classification task with data from multiple users.
In the past we trained a network per user. In case the number of users starts to increase then this will quickly become unfeasible. So we want to have a part of the model that is shared and another part that is user specific. One idea is to merge the bottom layers close to the input of the networks.

I looked at the issues about multiple output layers (#278 and #202) and the following gist
https://gist.github.com/DanChianucci/c37520b6f3d391eae447221e03093a1b.
The network in the gist has multiple output layers that are used to have two different classifications for the same input. This is slightly different in our case, because we only have one classification depending on the user. So the combined network should have multiple output layers, but  it is important that the gradient only flows in the user specific top part.

I included a picture to make it more clear:
![14585785_10210707208297796_1248846221_o](https://cloud.githubusercontent.com/assets/2494383/19172851/54e6f5cc-8c24-11e6-945a-51a145291bc0.jpeg)

Is there anybody who had the same problem?
Is it possible in nolearn?

Any help is welcome,

**Comment by BenjaminBossan** [comment]
Maybe you could use `theano.tensor.switch` to decide which branch to go. If that does not work, I'm sure you could fiddle with `nolearn.lasagne.base.objective` and decide there which of the two outputs to take, but that probably involve making a feedforward pass through both branches, which I guess you want to avoid.

**Comment by EliasVansteenkiste** [comment]
Thx @BenjaminBossan. I will check out theano.tensor.switch.
I indeed want to avoid the feedforward pass through both branches.
For 2 users this could still work but once the number of users starts to increase, it will not be feasible anymore.

**Comment by EliasVansteenkiste** [comment]
I will reopen the issue once i know more

**Comment by EliasVansteenkiste** [comment]
`theano.tensor.ifelse` is better than `theano.tensor.switch`, because ifelse is lazy and only evaluates the branches that have to be evaluated, switch evaluates both branches.

**Comment by BenjaminBossan** [comment]
Didn't know that, thanks for the update.
