### ISSUE TITLE
CUDA error, possibly related to network size?

### ISSUE THREAD

**Issue by ibeckermayer** [dnouri/nolearn#309]
I am attempting to train a deep neural network on a g2.2xlarge AWS instance with CUDA 7.5 installed, but keep on getting the following error message:

```terminal
mod.cu(5511) : cutilCheckMsg() CUTIL CUDA error : filterActs: kernel execution failed : (9) invalid configuration argument.
```

According to this pylearn2 thread (https://groups.google.com/forum/#!topic/pylearn-users/vjtyydH8T8w), this seems to have something to do with the number of conv units/filter size and the batch size, and how this interacts with theano. However, no matter how I change those parameters I keep on getting the same error. 

I'm wondering, is there some kind of general rule of thumb for the size of layers that I can use to ensure I don't cause this error? My network is defined as follows:

```python
def build_model():
    net = NeuralNet(
    layers=[
        ('input', layers.InputLayer),
        ('conv1', Conv2DLayer),
        ('pool1', MaxPool2DLayer),
        ('dropout1', layers.DropoutLayer),
        ('conv2', Conv2DLayer),
        ('pool2', MaxPool2DLayer),
        ('dropout2', layers.DropoutLayer),
        ('conv3', Conv2DLayer),
        ('pool3', MaxPool2DLayer),
        ('dropout3', layers.DropoutLayer),
        ('hidden4', layers.DenseLayer),
        ('dropout4', layers.DropoutLayer),
        ('hidden5', layers.DenseLayer),
        ('output', layers.DenseLayer),
        ],
    input_shape=(None, 1, 288, 288),
    conv1_num_filters=16, conv1_filter_size=(3, 3), pool1_pool_size=(2, 2),
    dropout1_p=0.1,
    conv2_num_filters=32, conv2_filter_size=(2, 2), pool2_pool_size=(2, 2),
    dropout2_p=0.2,
    conv3_num_filters=64, conv3_filter_size=(2, 2), pool3_pool_size=(2, 2),
    dropout3_p=0.3,
    hidden4_num_units=1000,
    dropout4_p=0.5,
    hidden5_num_units=1000,
    output_num_units=30, output_nonlinearity=None,

    update_learning_rate=theano.shared(float32(0.03)),
    update_momentum=theano.shared(float32(0.9)),

    regression=True,
    batch_iterator_train=BatchIterator(batch_size=32),
    on_epoch_finished=[
    AdjustVariable('update_learning_rate', start=0.03, stop=0.0001),
    AdjustVariable('update_momentum', start=0.9, stop=0.999),
    EarlyStopping(patience=200),
    ],
    max_epochs=3000,
    verbose=1,
    )

    return net
```

**Comment by BenjaminBossan** [comment]
Hi,

I'm not familiar with this error. The architecture looks fine, I don't believe that number of units or filter size have anything to do with the problem. Maybe what you could try is start with much smaller images (say 32x32) and get rid of all the "fancy" stuff like `on_epoch_finished`. Have you ever successfully trained a CNN on your server, say on MNIST?

Hope that helps find the error.

**Comment by ibeckermayer** [comment]
Hey, I was able to eventually get it to work using a different instance. No idea why that was happening. Thanks for taking a stab at it.
