### ISSUE TITLE
on_epoch_finished are not notified when fitting is complete

### ISSUE THREAD

**Issue by cancan101** [dnouri/nolearn#32]
Right now the list of functions in `on_epoch_finished` are called after each epoch but there is no explicit call to them to say training is complete. What that means is that something like [`EarlyStopping`](https://github.com/dnouri/kfkd-tutorial/blob/f6010a9feefd9af01e0afaeba1927a488ec90846/kfkd.py#L156) will never correctly transfer over the best weights if the StopIteration is not raised. What you probably want to do is to on training complete is `nn.load_weights_from(self.best_weights)` to leave the network with the best weights seen.

I suggest adding an extra callback:
`on_training_complete`

**Comment by dnouri** [comment]
I really need to get around documenting the interface.  (Been waiting for Lasagne to add names to layers so that I could simplify a few things before.)  But what you're looking for is already there and it's called `on_training_finished`.

**Comment by cancan101** [comment]
So in order to write early stopping to set best on training finished you would want to set the same early stopping object in both lists?

**Comment by dnouri** [comment]
You'd have to add a method `def load_best_weights(self, nn, train_history)` to `EarlyStopping` that does only the `nn.load_weights_from(self.best_weights)` call.  Then use that method in the on_epoch_finished handler: `on_epoch_finished=[early.load_best_weights]`.

**Comment by dnouri** [comment]
More concretely, this would be the extra method on `EarlyStopping`:
```python
    def load_best_weights(self, nn, train_history):
        nn.load_weights_from(self.best_weights)
```

I think it'll be useful to move `EarlyStopping` into nolearn itself (#18), in which case we might provide an implementation that has the above method, and documentation on how to use it.

Please reopen if you think this issue is still valid on its own.

**Comment by paipai880429** [comment]
Here is the origin of the early stopping. Concise!
