### ISSUE TITLE
Don't Pickle Theano Functions

### ISSUE THREAD

**Issue by cancan101** [dnouri/nolearn#33]
Discussion: http://danielnouri.org/notes/2014/12/17/using-convolutional-neural-nets-to-detect-facial-keypoints-tutorial/#comment-1775120366

Two part fix:
https://github.com/cancan101/nolearn/commit/f04308caaeebe6d5f7921973ae5f9b8d885e3826
https://github.com/cancan101/nolearn/commit/3f80b31a7d16699f518428bfae824f6c2a5a161c

**Comment by dnouri** [comment]
Hey Alex, can you provide a little more background to this?  I've checked the discussion you link to, but what's exactly the motivation for not storing these particular Theano functions?  After all, we're still keeping the `_output_layer` around, which looks like it's the bulkier part.  In fact, I've tried to pickle a small net and the difference in pickle size was neglectable.  Maybe you've had different results with your nets?  Or else, is there any other reason not to pickle these?

**Comment by cancan101** [comment]
I might start by turning the question around: is there any reason TO pickle these values? The network is fully specified without needing these functions (ie they are purely derived values from other values that are being store). You are basically creating larger pickle files and storing no additional information.

The downsides of pickling though are: the generated function may be specific to the settings of the computer used to fit (ie CPU vs GPU, optimization levels) and you actually do want to re-compile the function on unpickling. A example of this is a fit on a GPU cluster, save the fits and then reload them on a machine with CPU only.

The more pressing issue is that some of the Theano function simply will not pickle using the default pickling library. Sure there is dill, etc, but this seems like a hack in order to save a derived value. At the very least I would argue that the default is to just save the bear minimum to reload the net. If the user wants to "cache" the functions and save them (perhaps to avoid a recompile), that should be an opt in.

**Comment by dnouri** [comment]
Very good points.  Could you check and see if the pull request in #37 sufficiently solves this issue for you?
