### ISSUE TITLE
python 3 support not working with Lasagne?

### ISSUE THREAD

**Issue by vsoch** [dnouri/nolearn#335]
Hey @dnouri ! I saw in #28 that nolearn has python 3 support, but I'm having an issue installing with pip and Github:

```
2066b4973a1bd2b0ca2e5435f35/Lasagne-0.1.tar.gz (125kB)
    100% |################################| 133kB 21.2MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-hxqxg_bu/Lasagne/setup.py", line 10, in <module>
        CHANGES = open(os.path.join(here, 'CHANGES.rst')).read()
      File "/opt/conda/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 243: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-hxqxg_bu/Lasagne/
```
My version of Python:

```
(base) root@f5698f9d1127:/code# python --version
Python 3.6.8 :: Anaconda, Inc.
```
Have you seen this before? It looks like it has something to do with Lasagne.

**Comment by nick-youngblut** [comment]
In regards to this, I'm trying to add nolearn to conda-forge, and it depends on the `gdbn` package, which itself depends on `gnumpy`, which is py2 only and hasn't been maintained since 2013. Maybe there's a way to remove the `gdbn` dependency?

**Comment by vsoch** [comment]
Hmm, well [gnumpy](http://www.cs.toronto.edu/~tijmen/gnumpy.py) could be modified for Python 3, no? In that the source code is available for gdbn and gnumpy, we might just want to contact the authors and get permission to do so. If you look at the bio [here](http://www.cs.toronto.edu/~gdahl/) he also recommends using a different library provided by Google, [jax](https://github.com/google/jax).

**Comment by vsoch** [comment]
hey @georgedahl! I'm hoping it's okay that we are pinging you here - there is some interest to use nolearn, and the dependencies (`gnumpy` and `gdbn`) are not being maintained. Could we talk about some options for moving forward? Here are some ideas:

 - discuss how Jax (you mentioned in your bio) could be used instead of nolearn entirely
 - use an entirely different library for `gdbn` - it looks like it's providing activation functions, and a build function for a net.
 - create a GitHub release for `gdbn` that includes a refactored `gnumpy` updated for Python 3 - update nolearn to use it.
 - something else!

Thanks for your help!  I'm not actively using this library, but I'm an RSE at Stanford and many of our researchers might, so I'm happy to help however I can.

**Comment by BenjaminBossan** [comment]
@dnouri AFAICT, gdbn is not required to use nolearn with lasagne. Would it make sense to have a nolearn release that gets rid of the gdbn dependency?

**Comment by vsoch** [comment]
There is even commentary in [this module](https://github.com/dnouri/nolearn/blob/2ef346c869e80fc90247916e4aea5cfa7cf2edda/nolearn/dbn.py) to use lasagne, as dbn isn't supported. How about instead of having as an install requires, move to 

```python
# Fix this to whatever version is needed
GDBN_REQUIRES = (
    ('gdbn', {'min_version': None}),
)
...
          extras_require={
              'gbdn': [GDBN_REQUIRES],
          }
```
Then default install won't include it, but if you do something like `pip install nolearn[gdbn]` then you can get it.

**Comment by dnouri** [comment]
Sorry for the late reply.  Do you mind making a pull request that contains your suggested change?

**Comment by vsoch** [comment]
Yes I can definitely give it a try!

**Comment by vsoch** [comment]
here you go https://github.com/dnouri/nolearn/pull/337

**Comment by dnouri** [comment]
@vsoch @nick-youngblut Just uploaded 0.6.1 to PyPI, containing your changes.  Let me know how that works for you.

**Comment by vsoch** [comment]
I'm good to close this issue if @nick-youngblut is also happy! I am not actively working on the analysis I was previously, but I'll definitely come back and give it a try in the future.

**Comment by nick-youngblut** [comment]
I'm also fine with closing the issue

**Comment by vsoch** [comment]
Make it so! /insert Picard
