### ISSUE TITLE
Train on full dataset

### ISSUE THREAD

**Issue by msegala** [dnouri/nolearn#34]
I would like to train on a full dataset and was wondering if there is anything I need to do besides
eval_size=0.0?

Exactly when are the final weights saved, is it for the best validation score, best training score, last epoch, ect.?

Thank you for the help and great code!

**Comment by run2** [comment]
Thing is - when do you stop ? when you train on full data set.

**Comment by run2** [comment]
Also I am getting an error when I train on full data set.
/usr/lib/python2.7/dist-packages/numpy/core/_methods.py:55: RuntimeWarning: Mean of empty slice.
I only modified the train_test_split method in lasagne.py.

**Comment by msegala** [comment]
I have tried this out and after it runs I get the error:

Epoch  |  Train loss  |  Valid loss  |  Train / Val  |  Valid acc  |  Dur
--------|--------------|--------------|---------------|-------------|-------
/usr/lib64/python2.7/site-packages/numpy/core/_methods.py:55: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
     1  |    3.379510  |         nan  |          nan  |       nan%  |  267.6s
     2  |    2.429299  |         nan  |          nan  |       nan%  |  267.7s
     3  |    2.071116  |         nan  |          nan  |       nan%  |  267.4s
     4  |    1.854738  |         nan  |          nan  |       nan%  |  267.3s
     5  |    1.683506  |         nan  |          nan  |       nan%  |  267.1s
     6  |    1.568097  |         nan  |          nan  |       nan%  |  267.1s
     7  |    1.478959  |         nan  |          nan  |       nan%  |  267.1s
     8  |    1.407118  |         nan  |          nan  |       nan%  |  267.0s
     .......
Early stopping.
Best valid loss was inf at epoch 0.
Traceback (most recent call last):
  File "run_analysis.py", line 121, in <module>
    func(*sys.argv[2:])
  File "run_analysis.py", line 109, in fit
    model.fit(X, y)
  File "/home/segalam/TEST/src/nolearn/nolearn/lasagne.py", line 244, in fit
    self.train_loop(X, y)
  File "/home/segalam/TEST/src/nolearn/nolearn/lasagne.py", line 326, in train_loop
    func(self, self.train_history_)
  File "/home/segalam/TEST/src/lasagne/examples/helpers.py", line 277, in __call__
    nn.load_weights_from(self.best_weights)
  File "/home/segalam/TEST/src/nolearn/nolearn/lasagne.py", line 384, in load_weights_from
    w.get_value() if hasattr(w, 'get_value') else w for w in source]
TypeError: 'NoneType' object is not iterable

**Comment by takacsg84** [comment]
You should not use Early stopping if you have no evaluation set, since early stopping compares the costs on the evaluation set.

**Comment by msegala** [comment]
indeed, that fixes the error. Thanks!
