### ISSUE TITLE
the -1 in DBN(layer_sizes=[-1,...] applies only to first call to fit method

### ISSUE THREAD

**Issue by udibr** [dnouri/nolearn#4]
Setting -1 as the first list element in the layer_sizes parameter of the DBN class works when you first
call the fit method. If you latter call the fit method again with a data set with a different number of features the method will crash

**Comment by dnouri** [comment]
I'm afraid I cannot support `nolearn.dbn` any longer; it's already removed from master.  May I suggest you give `nolearn.lasagne` a try instead? It's got a lot of improvements over the `dbn` module.
