### ISSUE TITLE
BatchIterator.transform() could give copies?

### ISSUE THREAD

**Issue by takacsg84** [dnouri/nolearn#43]
Have you considered
```python
    def transform(self, Xb, yb):
        return Xb.copy(), yb.copy()
```
in BatchIterator class?
It doesn't look like a big computational overhead and it could be really convenient, since usually we don't wan't to transform the original input.

**Comment by dnouri** [comment]
Assuming that in your custom BatchIterator class, you'll override `transform` anyway, why not do the `copy()` in your own method, too?

**Comment by takacsg84** [comment]
I wanted to put a 'Question' label to the issue :)
What you said is of course possible, but to me it just seems more convenient to have the copy behavior by default, but the difference is really minor.
Thx for your consideration!

**Comment by dnouri** [comment]
OK, fine then.
