### ISSUE TITLE
Problem pickling convnet NeuralNet: Can't pickle <function values_eq_approx at 0x7f2d4bef4e60>: it's not found as theano.sandbox.cuda.opt.values_eq_approx

### ISSUE THREAD

**Issue by bmilde** [dnouri/nolearn#44]
I encounter the following error while pickling a convnet NeuralNet:

pickle.PicklingError: Can't pickle <function values_eq_approx at 0x7f2d4bef4e60>: it's not found as theano.sandbox.cuda.opt.values_eq_approx

This problem also surfaced somewhere in the comments at http://danielnouri.org/notes/2014/12/17/using-convolutional-neural-nets-to-detect-facial-keypoints-tutorial/

I'm using the original Conv and MaxPool implementations in Lasagne

from lasagne import layers
Conv2DLayer = layers.Conv2DLayer
MaxPool2DLayer = layers.MaxPool2DLayer

As a workaround, I can use https://pypi.python.org/pypi/dill. But it would be nice if I also could use the standard pickle interface.

**Comment by dnouri** [comment]
Copying myself from the [comments thread that you're referring to](http://danielnouri.org/notes/2014/12/17/using-convolutional-neural-nets-to-detect-facial-keypoints-tutorial/#comment-1770167906):

>  I'm seeing why this happens; values_eq_approx is referenced from one of your conv layers, but it's defined inside of another function, which causes this pickling error. Moving values_eq_approx outside, and into the module global namespace would fix your issue. I bet the friendly Theano people would accept a pull request to do just that.

>  The reason I never saw this problem is probably due to the fact that I never used the conv op implementation that you use and then tried to pickle.

>  I didn't know about dill, certainly good to know that it exists. And happy that this solves your problem in an easy way.

My suggestion would still be to try and land a patch in Theano.  Please reopen if you can think of any other practical way of fixing this.
