### ISSUE TITLE
No self.best_weights in the function train_loop() ?

### ISSUE THREAD

**Issue by paipai880429** [dnouri/nolearn#46]
It seems that the train_loop() function inside the NeuralNetwork does not provide a self.best_weights which save the ConvNet parameters for the highest validation accuracy along with the epoch iterations.
Or do I miss something? Hope someone could help. Thank you.

**Comment by cancan101** [comment]
It is correct that the train loop does not keep track of the best weights seen so far. That being said, "best" is not uniquely defined. Do you mean best classification score or best objective score? Or some other notion of best? That decision is left to the user.

You can add this functionality using something like I proposed in: https://github.com/dnouri/nolearn/issues/18#issuecomment-73437888 (heavily inspired by Daniel's implementation in his blog post) and then:
```python
    early_stopping = EarlyStopping(patience=100)

    net = NeuralNet(...
        on_epoch_finished=[
            early_stopping,
        ],
        on_training_finished=[early_stopping.load_best_weights]
     )
```

**Comment by dnouri** [comment]
Thanks for your comment.  I believe we can close this one now.

**Comment by paipai880429** [comment]
@cancan101 , thank you for your timely reply and you are right. This is defined by developer, which keeps the main function clean and makes it more flexible and extendible. Inspired by your early_stopping a lot. Also thanks @dnouri for your amazing blog post.
