### ISSUE TITLE
Enhancement: multiple input layers

### ISSUE THREAD

**Issue by bmilde** [dnouri/nolearn#52]
This recent commit allows to specify network architectures that a different from the standard tower architecture: https://github.com/dnouri/nolearn/commit/12f263ccf09d32c3b73eff3d6fbe96ce85631f1e

It would certainly also be interesting, if one could use multiple input layers. E.g. a convolutional neural network, which does representation merging with hand crafted features at its last fully connected layers.

Given that NeuralNet builds on lasagne, would something like that be feasible with lasagne at all?

**Comment by dnouri** [comment]
Yes, it's totally feasible with Lasagne, but nolearn.lasagne doesn't support it yet.  With Lasagne, what you can do when calling output_layer.get_output is to pass a mapping of `{layer: input}` and Lasagne will do the right thing.

**Comment by dnouri** [comment]
From [here](https://groups.google.com/d/msg/lasagne-users/Gzz6mArH1m4/ilEg2CgVV6gJ), here's a little diagram of how this could be done using a single input X, and two SliceLayers:

```
          InputLayer(both)
            /        \
SliceLayer(image)   SliceLayer(hog)
         |             |
  DenseLayers          |
          \           /
           ConcatLayer
               |
          DenseLayers
```

**Comment by dnouri** [comment]
Multiple input layers have been added with #106.  That pull request also has a usage example.
