### ISSUE TITLE
About Class order in predict_proba() ?

### ISSUE THREAD

**Issue by paipai880429** [dnouri/nolearn#55]
I know that nolearn.lasagne has already provided the ```use_label_encoder``` to quantize the class names(string type). However, I have never successfully enjoy such convenience since I always run into theano type errors. Then, I make a detour that I use **sklearn.label_encoding** to transform my ```y_train``` and then feed it to ```NeuralNet```. So my question is: when I call ```NeuralNet.predict_proba```, it will return a matrix of probabilities, right? The column values are those classes probabilities. What are the orders of these column classes ? Are the :0, 1, 2..., N ?

**Comment by dnouri** [comment]
The order should be the same as in `neuralnet.classes_`.  Not sure which theano type errors you're referring to, but I'll assume this issue can be closed.
