### ISSUE TITLE
Would layer visualization be considered in nolearn ?

### ISSUE THREAD

**Issue by paipai880429** [dnouri/nolearn#59]
Since we can train a ConvNet by nolearn.lasagne and save the trained weights. Will nolearn provide a visualization function that plots e.g. first weight ```W1``` as a figure? Usually it will be some edge detectors like shown in the paper "Visualization and Understanding Convolutional Network".

**Comment by BenjaminBossan** [comment]
Take a look at the new [visualize.py](https://github.com/dnouri/nolearn/blob/master/nolearn/lasagne/visualize.py) functions. Among others, you have *plot_conv_weights* that takes as first argument the layer whose weights you want to plot (layers can be found in the *layers_* dict of your net).

**Comment by paipai880429** [comment]
Many thanks for telling me such great function !
