### ISSUE TITLE
Zero divison error

### ISSUE THREAD

**Issue by tartavull** [dnouri/nolearn#6]
when running:
```python
# import the necessary packages
from sklearn.cross_validation import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn import datasets
from nolearn.dbn import DBN

# scale the data to the range [0, 1] and then construct the training
# and testing splits
(trainX, testX, trainY, testY) = train_test_split( features , targets , test_size = 0.33)
 
print trainX.shape
print trainY.shape

dbn = DBN(
[trainX.shape[1], 80, 80, trainY.shape[1]],
learn_rates = 0.3,
learn_rate_decays = 0.9,
epochs = 10,
verbose = 1)
dbn.fit(trainX, trainY)
 
# compute the predictions for the test data and show a classification
# report
preds = dbn.predict(testX)```

It fails for some reason I cannot find:

```
100%

---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-4-5324a7be4932> in <module>()
     19 epochs = 10,
     20 verbose = 1)
---> 21 dbn.fit(trainX, trainY)
     22 
     23 # compute the predictions for the test data and show a classification

/usr/local/lib/python2.7/dist-packages/nolearn/dbn.pyc in fit(self, X, y)
    388                 loss_funct,
    389                 self.verbose,
--> 390                 self.use_dropout,
    391                 )):
    392             losses_fine_tune.append(loss)

/usr/local/lib/python2.7/dist-packages/gdbn/dbn.pyc in fineTune(self, minibatchStream, epochs, mbPerEpoch, loss, progressBar, useDropout)
    207                 prog.tick()
    208             prog.done()
--> 209             yield sumErr/float(totalCases), sumLoss/float(totalCases)
    210 
    211     def totalLoss(self, minibatchStream, lossFuncts):

ZeroDivisionError: float division by zero

gnumpy: failed to import cudamat. Using npmat instead. No GPU will be used.
(1, 200)
(1, 125)
[DBN] fitting X.shape=(1, 200)
[DBN] layers [200, 80, 80, 125]
[DBN] Fine-tune...
```

**Comment by dnouri** [comment]
I'm afraid I cannot support `nolearn.dbn` any longer; it's already removed from master.  May I suggest you give `nolearn.lasagne` a try instead? It's got a lot of improvements over the `dbn` module.
