### ISSUE TITLE
Updated dbn => lasagne examples?

### ISSUE THREAD

**Issue by jrosebr1** [dnouri/nolearn#61]
Maybe I'm missing something the documentation, but now that the dbn package has been deprecated and removed, would it be possible for the previous dbn examples to be re-done using lasagne?

**Comment by thalesfc** [comment]
That would be great. I was looking for something like that too.

**Comment by Temmplar** [comment]
Me too.

**Comment by davidteleco** [comment]
I am also really interested. Is there any solution for this? Temporarily, where can I find the old dbn package? Thanks!

**Comment by jrosebr1** [comment]
You can still access the old dbn package in the 0.5b1 version. You pull down the rep and then:

`$ git checkout 0.5b1`

and you can go from there. Additionally, I have a [tutorial](http://www.pyimagesearch.com/2014/09/22/getting-started-deep-learning-python/) that uses the 0.5b1 version that might help you get started playing around with it.

**Comment by davidteleco** [comment]
Thank you! Unfortunately, I am using python 3.4 currently and there seems to be problems to import dbn and gnumpy. I think that I will mimic the design of a DBN network by doing the following: I will pre-train several sklearn.neural_network.BenoulliRBN networks (train one, project the dataset, train the next one and repeat). Afterwards, I will create a nolearn.lasagne.NeuralNet deep network and initialize its weights using those obtained from the RBNs. Finally, I will train the deep network as usual. Do you think it is viable?

**Comment by dnouri** [comment]
The `nolearn.dbn` module has finally been restored in master via #236.  There is no Python 3 support.
