### ISSUE TITLE
How to predict a continuous oupout ?

### ISSUE THREAD

**Issue by mayouf** [dnouri/nolearn#65]
Hi,

I have been struggling to predict a continuous output, here is my code:

import pandas.io.data as web
f=web.DataReader("ALU", 'yahoo')
f["cible"]=f["Close"].shift()
f.dropna(inplace=True)
x=f[[u'Open', u'High', u'Low', u'Close']]
y=f['cible']

from nolearn.dbn import DBN
r=DBN([-1,2,-1],output_act_funct='Sigmoid')
r.fit(x.values,y.values)
pred=r.predict(x.values)
np.unique(pred)

How can I get a this right ? I tried differents transfert function....nothing.

cheers,

Mayouf.k

**Comment by dnouri** [comment]
Sorry, we don't support the old nolearn.dbn module anymore.  I suggest you take a look at the newer `nolearn.lasagne` (for which I've written a tutorial that has continuous output).
