### ISSUE TITLE
ansi class no longer used

### ISSUE THREAD

**Issue by cancan101** [dnouri/nolearn#86]
After refactor, this is no longer used: https://github.com/dnouri/nolearn/blob/ef1e5b5a38a4c08ef89593f8c5aaf2a7ec0a957c/nolearn/lasagne/base.py#L37

**Comment by dnouri** [comment]
cc @BenjaminBossan

**Comment by dnouri** [comment]
I cleaned up that new tabulate code myself.  The colors are back with #88.  I'm not so sure anymore that adding tabulate has improved things much.  But factoring the logging code out into its own epoch handler and the ability to print a custom score when logging are improvements.

**Comment by BenjaminBossan** [comment]
If it were just for this, tabulate would not be very helpful. But hopefully, this [PR](https://github.com/dnouri/nolearn/pull/85) will one day be accepted, which also relies on tabulate:

I think that having a uniform way of printing information is a good idea. Also, not having to bother with string formatting is nice. Whether tabulate or something else is the best choice I'm not sure.
