### ISSUE TITLE
Ways to get the output of a certain layer?

### ISSUE THREAD

**Issue by YunshuLiu** [dnouri/nolearn#92]
Sorry to bother you, I have a question about getting the output of convolution or hidden layers.

* I am not very familiar with lasagne/nolearn functions, it seems to me that for a given dataset which I already had a model trained on it, I can get the output of a particular layer by calling function similar to this: `predict_proba = output_layer.get_output(X_batch, deterministic=True) `
but how to let the network know which layer I want?
I try to count the index of the layer I want to use and do:
```
layer_i = self.get_all_layers()[3]
for Xb, yb in self.batch_iterator_test(X):
    out.append(layer_i.get_output(Xb,deterministic=True))
```
However, it give me error ```float argument required, not TensorVariable```
Ideally, I want to write a function similar to predict_proba(self, X) which take X and layer name as input and return the output for that layer.
```
    def predict_proba(self, X):
        probas = []
        for Xb, yb in self.batch_iterator_test(X):
            probas.append(self.predict_iter_(Xb))
        return np.vstack(probas)
```
* Another similar question is how to get the parameters of a convolution layer, the dataset I am working on is 1 dimensional data, however, using one layer of convolution significantly improved the performance, I would like to see how original features are interacted in the convolution layer.

Thanks in advance:)

**Comment by dnouri** [comment]
Regarding your first question: there's an open pull request that adds a `transform` method that'll get you the output of a layer other than the output layer: #89.

Regarding getting the parameters of a conv layer:  Once you get hold of a layer, (use `nn.layers_['<layername>']`) you can call its `get_params` method, which will return a list of Theano shared variables, which have a `get_value` method.
